# number of last changes to the main information of the vessel
NUMBER_RECENT_CHANGES = 5

# status document
ISSUED = 2
PROCESSED = 3
NEED_MORE_INFO = 4
DECLINE = 5
CANCELED = 6

CAPTAIN_STAFF_POSITION = 1

VALID_NOMINATION_MONTHS = 1

VALID_NOTIFICATIONS_MONTHS = 2
