# Generated by Django 2.2 on 2020-01-16 18:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlankStrictReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_branch', models.CharField(max_length=7)),
                ('code_track_record', models.CharField(blank=True, max_length=7, null=True)),
                ('name_ukr', models.CharField(max_length=150)),
                ('name_eng', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('house_num', models.CharField(max_length=15)),
                ('index', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('FIO_director', models.CharField(blank=True, max_length=150, null=True)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('value_eng', models.CharField(max_length=100)),
                ('value_abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('code', models.IntegerField(blank=True, null=True)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('name_abbr', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('house_num', models.CharField(blank=True, max_length=10, null=True)),
                ('index', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_details', models.CharField(blank=True, max_length=200, null=True)),
                ('director_name', models.CharField(blank=True, max_length=200, null=True)),
                ('director_name_rodovoy', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_ukr', models.TextField()),
                ('value_eng', models.TextField()),
                ('value_abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExtentDiplomeUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
                ('priority', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FunctionForPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LimitationForMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Limitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('address', models.TextField()),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('leader', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NTZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_en', models.TextField()),
                ('name_abbr', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=150, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house_num', models.CharField(blank=True, max_length=10, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('requsites', models.CharField(blank=True, max_length=100, null=True)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('director_name_rodovoy', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('email2', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_port', models.CharField(max_length=7)),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('position_capitan_ukr', models.TextField()),
                ('position_capitan_eng', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_dkk', models.BooleanField(default=True)),
                ('team', models.CharField(blank=True, max_length=200, null=True)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PositionForExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
                ('summ', models.FloatField(blank=True, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=150)),
                ('name_eng', models.CharField(max_length=150)),
                ('for_service', models.CharField(max_length=200)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('code', models.IntegerField()),
                ('for_service', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocumentNZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeNZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Speciality')),
            ],
        ),
        migrations.AddField(
            model_name='speciality',
            name='type_document_nz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.TypeDocumentNZ'),
        ),
        migrations.CreateModel(
            name='RulesForPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disable', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Position')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Rank')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_regulatory', models.TextField()),
                ('limitation', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('value_eng', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Country')),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.TypeDocument'),
        ),
        migrations.AddField(
            model_name='rank',
            name='type_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.TypeRank'),
        ),
        migrations.AddField(
            model_name='position',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Rank'),
        ),
        migrations.CreateModel(
            name='NZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('name_abbr', models.CharField(max_length=100)),
                ('postal_address', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('phone_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_disable', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('type_nz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.TypeNZ')),
            ],
        ),
        migrations.CreateModel(
            name='LimitationForFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disable', models.BooleanField(default=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.FunctionForPosition')),
                ('limitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Limitations')),
            ],
        ),
        migrations.CreateModel(
            name='LevelQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
                ('type_NZ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.TypeNZ')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionAndLevelForPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_function', models.IntegerField()),
                ('is_disable', models.BooleanField(default=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.FunctionForPosition')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Level')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Position')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='FIOCapitanOfPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Port')),
            ],
        ),
        migrations.CreateModel(
            name='DoctrorInMedicalInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.MedicalInstitution')),
            ],
        ),
        migrations.CreateModel(
            name='DocsForPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('is_continue', models.BooleanField(default=False)),
                ('with_position', models.BooleanField(default=False)),
                ('for_service', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Position')),
            ],
        ),
        migrations.CreateModel(
            name='CourceForPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Course')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Position')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Committe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('FIO_main', models.CharField(max_length=150)),
                ('FIO_secretary', models.CharField(blank=True, max_length=150, null=True)),
                ('branch_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.BranchOffice')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Commisioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('committe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Committe')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Region')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizatedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO_ukr', models.CharField(max_length=255)),
                ('FIO_eng', models.CharField(max_length=255)),
                ('for_documents_ukr', models.CharField(max_length=255)),
                ('for_documents_eng', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.BranchOffice')),
            ],
        ),
    ]
