# Generated by Django 2.2 on 2020-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
            ],
        ),
    ]
