# Generated by Django 2.2 on 2020-01-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_id', models.IntegerField()),
                ('important', models.BooleanField()),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('area_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('region_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('area_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('region_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('area_en', models.CharField(blank=True, max_length=150, null=True)),
                ('region_en', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'managed': True,
                'db_table': '_cities',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_ru', models.CharField(blank=True, max_length=60, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=60, null=True)),
                ('title_en', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'managed': True,
                'db_table': '_countries',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_id', models.IntegerField()),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'managed': True,
                'db_table': '_regions',
            },
        ),
        migrations.AddField(
            model_name='port',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
