# Generated by Django 2.2 on 2020-01-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20200124_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='api_ntz_id',
            field=models.PositiveIntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ntz',
            name='okpo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
