# Generated by Django 2.2 on 2020-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20200128_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_type',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='value_eng',
            field=models.CharField(default='', max_length=255),
        ),
    ]
