# Generated by Django 2.2 on 2020-02-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20200130_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionForMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
        migrations.AddField(
            model_name='rank',
            name='is_dkk',
            field=models.BooleanField(default=True),
        ),
    ]
