# Generated by Django 2.2 on 2020-02-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20200204_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCommisioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='committe',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
