# Generated by Django 2.2 on 2020-02-25 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20200208_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='api_ntz_arr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
