# Generated by Django 2.2 on 2020-02-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_course_api_ntz_arr'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryground',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Rule'),
        ),
    ]
