# Generated by Django 2.2 on 2020-02-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_regulatoryground_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='level',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='directory.Level'),
        ),
    ]
