# Generated by Django 2.2 on 2020-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_position_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='experience_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='standarts_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
