# Generated by Django 2.2 on 2020-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20200303_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='priority',
            field=models.PositiveSmallIntegerField(default=255, null=True),
        ),
    ]
