# Generated by Django 2.2 on 2020-05-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_rank_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=500)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
    ]
