# Generated by Django 2.2 on 2020-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_educationform_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='summ',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
