# Generated by Django 2.2 on 2020-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_typedocument_summ'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntz',
            name='ntz_integration_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
