# Generated by Django 2.2 on 2020-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_ntz_ntz_integration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='name_eng',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
