# Generated by Django 2.2 on 2020-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_faculty_name_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityWorkBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
    ]
