# Generated by Django 2.2 on 2020-06-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_responsibilityworkbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibilityworkbook',
            name='is_not_conventional',
            field=models.BooleanField(default=False),
        ),
    ]
