# Generated by Django 2.2 on 2020-06-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_responsibilityworkbook_is_not_conventional'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
