# Generated by Django 2.2 on 2020-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code_for_parsing',
            field=models.FloatField(default=0),
        ),
    ]
