# Generated by Django 2.2 on 2020-06-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_course_code_for_parsing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntz',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
