# Generated by Django 2.2 on 2020-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_ntz_is_disable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfAccrualRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
