# Generated by Django 2.2 on 2020-07-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_typeofaccrualrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntz',
            name='is_red',
            field=models.BooleanField(default=False),
        ),
    ]
