# Generated by Django 2.2 on 2020-07-08 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_ntz_is_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofaccrualrules',
            name='document_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
