# Generated by Django 3.0.8 on 2020-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_typeofaccrualrules_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nz',
            name='is_red',
            field=models.BooleanField(default=False),
        ),
    ]
