# Generated by Django 3.0.8 on 2020-07-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_nz_is_red'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
