# Generated by Django 3.0.8 on 2020-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0026_remove_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='allowed_to_get',
            field=models.ManyToManyField(related_name='_position_allowed_to_get_+', to='directory.Position'),
        ),
        migrations.AddField(
            model_name='rank',
            name='allowed_to_get',
            field=models.ManyToManyField(related_name='_rank_allowed_to_get_+', to='directory.Rank'),
        ),
    ]
