# Generated by Django 3.0.8 on 2020-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0028_auto_20200721_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='allowed_to_get',
            field=models.ManyToManyField(related_name='allowed_from', to='directory.Position'),
        ),
    ]
