# Generated by Django 2.2 on 2020-07-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_auto_20200721_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelqualification',
            name='course_time_hours',
            field=models.FloatField(default=0),
        ),
    ]
