# Generated by Django 2.2 on 2020-07-31 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0030_levelqualification_course_time_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='ntz',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
