# Generated by Django 2.2 on 2020-08-09 10:25

from django.db import migrations, models
from django.contrib.contenttypes.management import create_contenttypes

def update_content_type(apps, schema_editor):
    app = apps.get_app_config('directory')
    app.models_module = app.models_module or True
    create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='typecontact', app_label='sailor')
    new_ct = ContentType.objects.get(model='typecontact', app_label='directory')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0031_auto_20200731_1022'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='TypeContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]
