# Generated by Django 2.2 on 2020-08-09 12:13
import django.contrib.contenttypes.management
from django.db import migrations, models


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('directory')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='sex', app_label='sailor')
    new_ct = ContentType.objects.get(model='sex', app_label='directory')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0032_typecontact'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_ukr', models.CharField(max_length=20)),
                ('value_eng', models.CharField(max_length=20)),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]
