# Generated by Django 2.2 on 2020-08-09 13:28
import django.contrib.contenttypes.management
from django.db import migrations, models


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('directory')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    models = ['modeofnavigation', 'typegeu', 'typevessel']
    for model in models:
        old_ct = ContentType.objects.get(model=model, app_label='sailor')
        new_ct = ContentType.objects.get(model=model, app_label='directory')
        old_ct.app_label = new_ct.app_label
        new_ct.delete()
        old_ct.save(force_update=True)

class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0033_sex'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='ModeOfNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeGeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=10)),
                ('name_eng', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]
