# Generated by Django 2.2 on 2020-08-10 16:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('directory')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='experincefordkk', app_label='sailor')
    new_ct = ContentType.objects.get(model='experincefordkk', app_label='directory')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0034_modeofnavigation_typegeu_typevessel'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='ExperinceForDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experince_value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('experince_descr', models.TextField(blank=True, null=True)),
                ('standarts_text', models.TextField(blank=True, null=True)),
                ('month_required', models.PositiveSmallIntegerField(default='6')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Position')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]
