# Generated by Django 2.2 on 2020-08-25 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('document', '0021_auto_20200825_1625'),
        ('directory', '0035_experincefordkk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commisioner',
            name='committe',
        ),
        migrations.AddField(
            model_name='commisioner',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commisioner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commisioner',
            name='name',
            field=models.CharField(max_length=250),
        ),
        # migrations.DeleteModel(
        #     name='Committe',
        # ),
    ]
