# Generated by Django 3.1 on 2020-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0036_auto_20200825_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='requisites',
            field=models.TextField(default=''),
        ),
    ]
