# Generated by Django 3.1 on 2020-08-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0037_branchoffice_requisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commisioner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    unique=True),
        ),
    ]
