# Generated by Django 3.1 on 2020-09-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0038_auto_20200828_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ntz',
            old_name='name_en',
            new_name='name_eng',
        ),
        migrations.RenameField(
            model_name='ntz',
            old_name='name',
            new_name='name_ukr',
        ),
        migrations.RemoveField(
            model_name='ntz',
            name='director_name_rodovoy',
        ),
        migrations.RemoveField(
            model_name='ntz',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='ntz',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='ntz',
            name='house_num',
        ),
        migrations.RemoveField(
            model_name='ntz',
            name='index',
        ),
        migrations.RenameField(
            model_name='ntz',
            old_name='requsites',
            new_name='requisites',
        ),
        migrations.RenameField(
            model_name='ntz',
            old_name='street',
            new_name='address',
        ),
        migrations.AddField(
            model_name='ntz',
            name='accountant_full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ntz',
            name='direction_position',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ntz',
            name='inn',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='ntz',
            name='mfo',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='ntz',
            name='nds_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ntz',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='ntz',
            name='director_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ntz',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ntz',
            name='name_abbr',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ntz',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='ntz',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='experincefordkk',
            name='experince_value',
            field=models.JSONField(),
        ),
    ]
