# Generated by Django 3.1 on 2020-09-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0039_auto_20200901_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntz',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ntz',
            name='requisites',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
