# Generated by Django 3.1 on 2020-09-01 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0040_auto_20200901_1344'),
    ]

    operations = [
    ]
