# Generated by Django 3.1 on 2020-09-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0041_remove_ntz_ntz_integration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntz',
            name='contract_number_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ntz',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ntz',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
