# Generated by Django 3.1 on 2020-09-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0042_auto_20200901_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntz',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ntz',
            name='check_number',
            field=models.CharField(default='', max_length=60),
        ),
    ]
