# Generated by Django 3.1 on 2020-09-01 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0043_auto_20200901_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ntz',
            old_name='direction_position',
            new_name='director_position',
        ),
    ]
