# Generated by Django 3.1 on 2020-09-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0044_auto_20200901_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='continue_merge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_continue',
            field=models.BooleanField(default=False),
        ),
    ]
