# Generated by Django 3.1 on 2020-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0045_auto_20200910_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntz',
            name='can_pay_platon',
            field=models.BooleanField(default=False),
        ),
    ]
