# Generated by Django 3.1 on 2020-10-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0032_auto_20201010_1553'),
        ('directory', '0046_ntz_can_pay_platon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllCommisioner',
        ),
        migrations.DeleteModel(
            name='Committe',
        ),
    ]
