# Generated by Django 3.1 on 2020-10-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0047_auto_20201010_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourceForPosition',
        ),
    ]
