# Generated by Django 3.1 on 2020-10-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0048_delete_courceforposition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtentDiplomeUniversity',
            new_name='ExtentDiplomaUniversity',
        ),
    ]
