# Generated by Django 3.1 on 2020-10-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0049_auto_20201010_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='summ',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='typedocument',
            old_name='summ',
            new_name='price',
        ),
    ]
