# Generated by Django 3.1 on 2020-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0050_auto_20201010_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='okpo',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
