# Generated by Django 3.1.1 on 2020-11-02 08:25

from django.db import migrations, models


def create_default_table(apps, schema_editor):
    for_sevrices = ['MedicalCertificate', 'ServiceRecord', 'Education', 'LineInServiceRecord',
                    'QualificationDocument', 'SailorPassport', 'ProofOfDiploma']
    statuses = (
        {'name_ukr': 'Прийнято', 'name_eng': 'Accepted'},
        {'name_ukr': 'В обробці', 'name_eng': 'In process'},
        {'name_ukr': 'Схвалено', 'name_eng': 'Approved'},
    )
    StatusDocumentInVerification = apps.get_model('directory', 'StatusDocumentInVerification')
    for service in for_sevrices:
        order_num = 1
        for status in statuses:
            status['for_service'] = service
            status['order_number'] = order_num
            StatusDocumentInVerification.objects.create(**status)
            order_num += 1


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0051_branchoffice_okpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDocumentInVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=150)),
                ('name_eng', models.CharField(max_length=150)),
                ('is_disable', models.BooleanField(default=False)),
                ('for_service', models.CharField(max_length=200)),
                ('order_number', models.IntegerField()),
            ],
            options={
                'unique_together': {('for_service', 'order_number')},
            },
        ),
        migrations.RunPython(create_default_table),
    ]
