# Generated by Django 3.1.1 on 2020-11-04 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sailor', '0137_documentinverification_verificationcomment'),
        ('directory', '0052_statusdocumentinverification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusDocumentInVerification',
            new_name='VerificationStage',
        ),
        migrations.AlterUniqueTogether(
            name='verificationstage',
            unique_together={('order_number', 'for_service')},
        ),
    ]
