# Generated by Django 3.1.1 on 2020-11-04 13:07

import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


def create_default_table(apps, schema_editor):
    for_sevrices = [
        ('document', 'MedicalCertificate'),
        ('document', 'ServiceRecord',),
        ('document', 'Education'),
        ('document', 'LineInServiceRecord'),
        ('document', 'QualificationDocument'),
        ('sailor', 'SailorPassport'),
        ('document', 'ProofOfDiploma'),
    ]

    VerificationStage = apps.get_model('directory', 'VerificationStage')
    for app, model_name in for_sevrices:
        if model_name == 'ProofOfDiploma':
            model = apps.get_model(app, 'ProofOfWorkDiploma')
            content_type = ContentType.objects.get_for_model(model)
        else:
            model = apps.get_model(app, model_name)
            content_type = ContentType.objects.get_for_model(model)
        VerificationStage.objects.filter(for_service=model_name).update(for_service=content_type.pk)


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directory', '0053_auto_20201104_1313'),
    ]

    operations = [
        migrations.RunPython(create_default_table),
        migrations.AlterField(
            model_name='verificationstage',
            name='for_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]
