# Generated by Django 3.1 on 2020-11-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directory', '0054_auto_20201104_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstage',
            name='for_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]

