# Generated by Django 3.1 on 2020-12-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0055_auto_20201110_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofaccrualrules',
            name='type_sailor',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Cadet')], default=0),
        ),
    ]
