# Generated by Django 3.1.1 on 2020-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requied_2fa',
        ),
        migrations.AddField(
            model_name='user',
            name='type_authorization',
            field=models.CharField(choices=[('admin', 'admin'), ('agent', 'agent')], default='basic', max_length=15),
        ),
    ]
