# Generated by Django 3.1.1 on 2020-09-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200909_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='%Y-%m-%d/')),
                ('type_photo', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
