# Generated by Django 3.1.1 on 2020-09-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='file',
        ),
    ]
