# Generated by Django 3.1.1 on 2020-10-09 13:55

import django.utils.timezone
import pgcrypto.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20201009_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(
                choices=[('admin', 'admin'), ('agent', 'agent'), ('marad', 'marad'), ('head_agency', 'head_agency'),
                         ('harbor_master', 'harbor_master'), ('port_worker', 'port_worker')], default='agent',
                max_length=15),
        ),
        migrations.CreateModel(
            name='HeadAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='head_agency',
                                                to='core.agency')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agent',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents',
                                    to='core.agency'),
        ),
        migrations.DeleteModel(
            name='UserAgency',
        ),
    ]
