# Generated by Django 3.1.1 on 2020-10-09 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20201009_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent',
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='harbormaster',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harbor_master',
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='headagency',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agency_user',
                                       to='core.agency'),
        ),
        migrations.AlterField(
            model_name='headagency',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_agency',
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portworker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='port_worker',
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermarad',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_marad',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
