# Generated by Django 3.1.1 on 2020-10-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0008_agency'),
        ('core', '0007_auto_20201009_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents',
                                    to='directory.agency'),
        ),
        migrations.AlterField(
            model_name='headagency',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agency_user',
                                       to='directory.agency'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
