# Generated by Django 3.1 on 2020-10-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20201009_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortWorker',
            new_name='HarborWorker',
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(
                choices=[('admin', 'admin'), ('agent', 'agent'), ('marad', 'marad'), ('head_agency', 'head_agency'),
                         ('harbor_master', 'harbor_master'), ('harbor_worker', 'harbor_worker')], default='agent',
                max_length=15),
        ),
    ]
