# Generated by Django 3.1 on 2020-10-12 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20201012_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harborworker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harbor_worker',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
