# Generated by Django 3.1 on 2020-10-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0009_contacts'),
        ('core', '0010_auto_20201012_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='harbormaster',
            name='port',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.port'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harborworker',
            name='port',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.port'),
            preserve_default=False,
        ),
    ]
