# Generated by Django 3.1 on 2020-10-12 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_auto_20201012_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='harbormaster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='harbormaster',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='harborworker',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='harborworker',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='headagency',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='headagency',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='usermarad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usermarad',
            name='modified_at',
        ),
    ]
