# Generated by Django 3.1 on 2020-10-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0011_agency_author'),
        ('core', '0014_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.agency'),
            preserve_default=False,
        ),
    ]
