# Generated by Django 3.1 on 2020-10-15 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_userinvitation_agency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInvitation',
        ),
    ]
