# Generated by Django 3.1.1 on 2020-11-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('admin', 'admin'), ('agent', 'agent'), ('user_marad', 'user_marad'), ('head_agency', 'head_agency'), ('harbor_master', 'harbor_master'), ('harbor_worker', 'harbor_worker'), ('accountant', 'accountant')], default='agent', max_length=15),
        ),
    ]
