# Generated by Django 3.1.1 on 2020-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201110_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_changed_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headagency',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
