# Generated by Django 3.1.1 on 2020-11-20 13:59

from django.db import migrations, models


def create_start_date(apps, schema_editor):
    Agent = apps.get_model('core', 'Agent')
    Agent.objects.update(is_changed_password=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201120_1359'),
    ]

    operations = [
        migrations.RunPython(create_start_date)
    ]
