# Generated by Django 3.1.1 on 2020-12-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201123_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='harbormaster',
            name='cifra_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='usermarad',
            name='cifra_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
