# Generated by Django 3.1.1 on 2020-12-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201223_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='harbormaster',
            name='cifra_person',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='usermarad',
            name='cifra_person',
            field=models.UUIDField(null=True),
        ),
    ]
