# Generated by Django 3.1.1 on 2020-12-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201229_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cifra_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='agent',
            name='cifra_person',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='headagency',
            name='cifra_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='headagency',
            name='cifra_person',
            field=models.UUIDField(null=True),
        ),
    ]
