# Generated by Django 3.1.1 on 2020-12-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201231_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cifra_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
