# Generated by Django 3.1.1 on 2021-01-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201231_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harbormaster',
            name='port',
        ),
    ]
