# Generated by Django 3.1.1 on 2021-01-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_harbormaster_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_changed_password',
        ),
        migrations.AddField(
            model_name='user',
            name='is_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
