# Generated by Django 3.1.1 on 2021-01-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_auto_20210121_0722'),
        ('core', '0026_auto_20210122_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='directory.agency'),
        ),
        migrations.AlterField(
            model_name='harborworker',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.port'),
        ),
        migrations.AlterField(
            model_name='headagency',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_user', to='directory.agency'),
        ),
    ]
