# Generated by Django 3.1.1 on 2021-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210122_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='headagency',
            name='accept_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
