# Generated by Django 3.1.1 on 2021-01-27 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    replaces = [('core', '0029_borderguard_portmanager'), ('core', '0030_auto_20210127_1326')]

    dependencies = [
        ('core', '0028_headagency_accept_agreement'),
        ('directory', '0019_auto_20210126_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_managers', to='directory.port')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='port_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BorderGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_guards', to='directory.port')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='border_guard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('admin', 'admin'), ('agent', 'agent'), ('user_marad', 'user_marad'), ('head_agency', 'head_agency'), ('harbor_master', 'harbor_master'), ('harbor_worker', 'harbor_worker'), ('accountant', 'accountant'), ('border_guard', 'border_guard'), ('port_manager', 'port_manager')], default='agent', max_length=15),
        ),
    ]
