# Generated by Django 3.1.1 on 2021-02-01 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    replaces = [('core', '0032_auto_20210129_1024'), ('core', '0033_auto_20210129_1104')]

    dependencies = [
        ('directory', '0020_towingcompany_towingcompanydocs'),
        ('core', '0031_auto_20210129_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('admin', 'admin'), ('agent', 'agent'), ('user_marad', 'user_marad'), ('head_agency', 'head_agency'), ('harbor_master', 'harbor_master'), ('harbor_worker', 'harbor_worker'), ('accountant', 'accountant'), ('border_guard', 'border_guard'), ('port_manager', 'port_manager'), ('head_towing', 'head_towing')], default='agent', max_length=15),
        ),
        migrations.CreateModel(
            name='HeadTowingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250)),
                ('inn', models.CharField(blank=True, default='', max_length=12)),
                ('cifra_person', models.UUIDField(null=True)),
                ('cifra_key', models.CharField(blank=True, default='', max_length=512)),
                ('towing_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_towing', to='directory.towingcompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_towing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
