# Generated by Django 2.2 on 2020-06-25 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0019_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETIRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('number_protocol', models.IntegerField()),
                ('is_disable', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.NTZ')),
            ],
        ),
    ]
