# Generated by Django 2.2 on 2020-07-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_ntz_is_disable'),
        ('certificates', '0002_auto_20200630_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='etiregistry',
            unique_together={('institution', 'course', 'date_start', 'date_end', 'number_protocol')},
        ),
    ]
