# Generated by Django 3.0.8 on 2020-07-24 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_auto_20200721_1841'),
        ('certificates', '0003_auto_20200701_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_history', to='directory.NTZ')),
            ],
        ),
    ]
