# Generated by Django 2.2 on 2020-07-30 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_auto_20200724_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiregistry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eti_registry', to='directory.Course'),
        ),
    ]
