# Generated by Django 2.2 on 2020-07-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_auto_20200721_1841'),
        ('certificates', '0006_auto_20200730_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeForCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_hours', models.FloatField(default=0)),
                ('practice_hours', models.FloatField(default=0)),
                ('examination_hours', models.FloatField(default=0)),
                ('is_continue', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Course')),
            ],
        ),
    ]
