# Generated by Django 2.2 on 2020-07-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0030_levelqualification_course_time_hours'),
        ('certificates', '0007_timeforcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeforcourse',
            unique_together={('course', 'is_continue')},
        ),
    ]
