# Generated by Django 3.1 on 2020-10-22 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_auto_20200923_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiregistry',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='etiregistry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
