# Generated by Django 3.1 on 2020-10-22 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_auto_20201022_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateredhistory',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
