# Generated by Django 3.1 on 2020-10-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_auto_20201022_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateredhistory',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
