# Generated by Django 3.1 on 2020-10-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_auto_20201022_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateredhistory',
            options={'ordering': ['-created_at', '-modified_at']},
        ),
        migrations.RenameField(
            model_name='certificateredhistory',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='certificateredhistory',
            old_name='date_modified',
            new_name='modified_at',
        ),
    ]
