# Generated by Django 2.2 on 2020-08-09 12:21
import django.contrib.contenttypes.management
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields
import user_profile.mixins


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('document')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='servicerecord', app_label='sailor')
    new_ct = ContentType.objects.get(model='servicerecord', app_label='document')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0033_sex'),
        ('sailor', '0106_auto_20200809_1520')
    ]

    state_operations = [
        migrations.CreateModel(
            name='ServiceRecordSailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('issued_by', models.TextField()),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('auth_agent_ukr', models.CharField(max_length=200)),
                ('auth_agent_eng', models.CharField(max_length=200)),
                ('date_issued', models.DateField()),
                ('blank_strict_report', models.BigIntegerField(blank=True, null=True)),
                ('waibill_number', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to=settings.AUTH_USER_MODEL)),
                ('branch_office',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.BranchOffice')),
                ('status',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
            options={
                'verbose_name': 'Послужна книжка моряка',
            },
            bases=(user_profile.mixins.GetAuthorMixin, models.Model),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]
