# Generated by Django 2.2 on 2020-08-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_lineinservicerecord'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='lineinservicerecord',
        #     name='mode_of_navigation',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='lineinservicerecord',
        #     name='type_geu',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='lineinservicerecord',
        #     name='type_vessel',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
