# Generated by Django 2.2 on 2020-08-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20200809_1626'),
        ('sailor', '0111_auto_20200809_1627'),
        ('directory', '0034_modeofnavigation_typegeu_typevessel')
    ]

    operations = [
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='mode_of_navigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.ModeOfNavigation'),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='type_geu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.TypeGeu'),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='type_vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.TypeVessel'),
        ),
    ]
