# Generated by Django 2.2 on 2020-08-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields
import user_profile.mixins


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('document')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='medicalsertificate', app_label='sailor')
    new_ct = ContentType.objects.get(model='medicalsertificate', app_label='document')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)

class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0035_experincefordkk'),
        ('statement', '0010_auto_20200811_1812'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0007_sertificatentz'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='MedicalSertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_end', models.DateField()),
                ('date_start', models.DateField()),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.DoctrorInMedicalInstitution')),
                ('limitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.LimitationForMedical')),
                ('medical_statement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='statement.StatementMedicalCertificate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.PositionForMedical')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
            options={
                'verbose_name': 'Медична справка',
            },
            bases=(user_profile.mixins.GetAuthorMixin, models.Model),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)

    ]

