# Generated by Django 2.2 on 2020-08-13 21:19

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields
import user_profile.mixins


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('document')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='qualitifcationdocument', app_label='sailor')
    new_ct = ContentType.objects.get(model='qualitifcationdocument', app_label='document')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statement', '0010_auto_20200811_1812'),
        ('directory', '0035_experincefordkk'),
        ('document', '0008_medicalsertificate'),
        ('docs', '0012_auto_20200814_0015'),
        ('sailor', '0120_auto_20200814_0018')
    ]

    state_operations = [
        migrations.CreateModel(
            name='QualitifcationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_document', models.BigIntegerField(blank=True, null=True)),
                ('other_number', models.CharField(blank=True, max_length=50, null=True)),
                ('list_positions',
                 django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('other_port', models.CharField(blank=True, max_length=250, null=True)),
                ('fio_captain_ukr', models.CharField(blank=True, max_length=200, null=True)),
                ('fio_captain_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('new_document', models.BooleanField(default=True)),
                ('function_limitation', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('strict_blank', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to=settings.AUTH_USER_MODEL)),
                ('country',
                 models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='directory.Country')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                           to='directory.Port')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='directory.Position')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.Rank')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                to='statement.StatemenetQualificationDocument')),
                ('status_document',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
                ('type_document',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.TypeDocument')),
            ],
            options={
                'verbose_name': 'Кваліфікаційний документ',
            },
            bases=(user_profile.mixins.GetAuthorMixin, models.Model),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type),
        migrations.RunSQL(
            'alter table sailor_qualitifcationdocument_related_docs rename '
            'to document_qualitifcationdocument_related_docs;'
        )

    ]
