# Generated by Django 2.2 on 2020-08-14 08:18

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields
import user_profile.mixins


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('document')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='proofofworkdiploma', app_label='sailor')
    new_ct = ContentType.objects.get(model='proofofworkdiploma', app_label='document')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0010_auto_20200811_1812'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0035_experincefordkk'),
        ('document', '0009_qualitifcationdocument'),
        ('sailor', '0122_auto_20200814_1116'),
        ('docs', '0014_auto_20200814_1116')
    ]

    state_operations = [
        migrations.CreateModel(
            name='ProofOfWorkDiploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_document', models.BigIntegerField(blank=True, null=True)),
                ('other_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('is_continue', models.IntegerField(default=0)),
                ('other_port', models.CharField(blank=True, max_length=250, null=True)),
                ('fio_captain_ukr', models.CharField(blank=True, max_length=200, null=True)),
                ('fio_captain_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('strict_blank', models.CharField(blank=True, max_length=30, null=True)),
                ('function_limitation', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('diploma_year', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.QualitifcationDocument')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Port')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statement.StatemenetQualificationDocument')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
            options={
                'verbose_name': 'Підтвердження к диплому',
            },
            bases=(user_profile.mixins.GetAuthorMixin, models.Model),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]