# Generated by Django 2.2 on 2020-08-14 08:44

from django.db import migrations, models
import django.db.models.deletion

def update_content_type(apps, schema_editor):
    app = apps.get_app_config('document')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='responsibilityservicerecord', app_label='sailor')
    new_ct = ContentType.objects.get(model='responsibilityservicerecord', app_label='document')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0035_experincefordkk'),
        ('document', '0010_proofofworkdiploma'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='ResponsibilityServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('days_work', models.IntegerField(blank=True, null=True)),
                ('is_repaired', models.BooleanField(default=False)),
                ('responsibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Responsibility')),
                ('service_record_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_record_line', to='document.LineInServiceRecord')),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]