# Generated by Django 2.2 on 2020-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0012_auto_20200822_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='service_record',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
