# Generated by Django 2.2 on 2020-08-22 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0013_auto_20200822_1621'),
    ]

    operations = [
        migrations.RenameModel('ServiceRecordSailor', 'ServiceRecord')
    ]
