# Generated by Django 2.2 on 2020-08-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0014_auto_20200822_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='service_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='lines', to='document.ServiceRecord'),
        ),
    ]
