# Generated by Django 2.2 on 2020-08-22 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0015_auto_20200822_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='status',
            new_name='status_document',
        ),
    ]
