# Generated by Django 2.2 on 2020-08-22 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0016_auto_20200822_1643'),
    ]

    operations = [
        migrations.RenameModel('SailorEducation', 'Education')
    ]
