# Generated by Django 2.2 on 2020-08-22 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0017_auto_20200822_1655'),
    ]

    operations = [
        migrations.RenameModel('ProtocolDKK', 'ProtocolSQC')
    ]
