# Generated by Django 2.2 on 2020-08-22 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0018_auto_20200822_1729'),
    ]

    operations = [
        migrations.RenameModel('SertificateNTZ', 'CertificateETI')
    ]
