# Generated by Django 2.2 on 2020-08-24 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0019_auto_20200822_1803'),
    ]

    operations = [
        migrations.RunSQL('alter table document_protocoldkk_related_docs rename to'
                          ' document_protocolsqc_related_docs;')
    ]
