# Generated by Django 3.1 on 2020-09-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0013_auto_20200829_1927'),
        ('document', '0022_auto_20200826_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateeti',
            name='statement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='statement.statementeti'),
        ),
    ]
