# Generated by Django 3.1 on 2020-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0023_certificateeti_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolsqc',
            name='statement_dkk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
