# Generated by Django 3.1 on 2020-10-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0026_auto_20201010_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='diploma',
            field=models.IntegerField(),
        ),
    ]
