# Generated by Django 3.1 on 2020-10-10 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0017_auto_20201010_1153'),
        ('directory', '0046_ntz_can_pay_platon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0027_auto_20201010_1306'),
        ('docs', '0020_auto_20201010_1306')
    ]

    operations = [
        migrations.RenameModel(
            old_name='QualitifcationDocument',
            new_name='QualificationDocument',
        ),
    ]
