# Generated by Django 3.1 on 2020-10-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0028_auto_20201010_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='diploma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.qualificationdocument'),
        ),
    ]
