# Generated by Django 3.1 on 2020-10-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0029_auto_20201010_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='statement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationdocument',
            name='statement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
