# Generated by Django 3.1 on 2020-10-10 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0018_auto_20201010_1317'),
        ('document', '0030_auto_20201010_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='statement.statementqualification'),
        ),
        migrations.AlterField(
            model_name='qualificationdocument',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='statement.statementqualification'),
        ),
    ]
