# Generated by Django 3.1 on 2020-10-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0031_auto_20201010_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolsqc',
            name='commisioners',
        ),
        migrations.RemoveField(
            model_name='protocolsqc',
            name='committe',
        ),
    ]
