# Generated by Django 3.1 on 2020-10-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0032_auto_20201010_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificateeti',
            old_name='course_traning',
            new_name='course_training',
        ),
    ]
