# Generated by Django 3.1 on 2020-10-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0033_auto_20201010_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='extent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
