# Generated by Django 3.1 on 2020-10-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0049_auto_20201010_1613'),
        ('document', '0034_auto_20201010_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='extent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.extentdiplomauniversity'),
        ),
    ]
