# Generated by Django 3.1 on 2020-10-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0035_auto_20201010_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='experied_date',
            new_name='expired_date',
        ),
    ]
