# Generated by Django 3.1 on 2020-10-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0036_auto_20201010_1629'),
    ]

    operations = [
        migrations.RunSQL('alter table document_qualitifcationdocument_related_docs rename to '
                          'document_qualificationdocument_related_docs;')
    ]
