# Generated by Django 3.1 on 2020-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0038_auto_20201022_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolsqc',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='protocolsqc',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
