# Generated by Django 3.1 on 2020-10-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0039_auto_20201022_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificateeti',
            old_name='date_create',
            new_name='created_at',
        ),
    ]
