# Generated by Django 3.1 on 2020-10-22 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0040_auto_20201022_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateeti',
            options={'ordering': ['-created_at', '-modified_at']},
        ),
        migrations.AddField(
            model_name='certificateeti',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificateeti',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
