# Generated by Django 3.1 on 2020-10-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import itcs.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0043_auto_20201028_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='author',
            field=models.ForeignKey(default=itcs.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='author',
            field=models.ForeignKey(default=itcs.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='author',
            field=models.ForeignKey(default=itcs.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='author',
            field=models.ForeignKey(default=itcs.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualificationdocument',
            name='author',
            field=models.ForeignKey(default=itcs.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='author',
            field=models.ForeignKey(default=itcs.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
