# Generated by Django 3.1 on 2020-11-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0044_auto_20201030_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created_at', '-modified_at'], 'permissions': (('merge_education_documents', 'Слитие образовательных документов'),), 'verbose_name': 'Освітні документи'},
        ),
        migrations.AlterModelOptions(
            name='qualificationdocument',
            options={'ordering': ['-created_at', '-modified_at'], 'permissions': (('merge_qualification_documents', 'Слитие квалификационных документов'),), 'verbose_name': 'Кваліфікаційний документ'},
        ),
    ]
