# Generated by Django 3.1 on 2020-11-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0055_auto_20201110_1743'),
        ('document', '0045_auto_20201111_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolsqc',
            name='decision',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.decision'),
        ),
    ]
