# Generated by Django 3.1 on 2020-12-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0046_auto_20201119_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateeti',
            name='is_only_dpd',
            field=models.BooleanField(default=False),
        ),
    ]
