# Generated by Django 2.2 on 2020-08-08 08:22

import datetime

import django.contrib.contenttypes.management
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('statement')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='statementservicerecord', app_label='sailor')
    new_ct = ContentType.objects.get(model='statementservicerecord', app_label='statement')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directory', '0031_auto_20200731_1022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sailor', '0083_auto_20200808_1118')
    ]

    state_operations = [
        migrations.CreateModel(
            name='StatementServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sailor', pgcrypto.fields.IntegerPGPSymmetricKeyField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='contenttypes.ContentType')),
                ('status',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]
