# Generated by Django 2.2 on 2020-08-08 13:55
import django.contrib.contenttypes.management
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def update_content_type(apps, schema_editor):
    app = apps.get_app_config('statement')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    old_ct = ContentType.objects.get(model='statementeti', app_label='sailor')
    new_ct = ContentType.objects.get(model='statementeti', app_label='statement')
    old_ct.app_label = new_ct.app_label
    new_ct.delete()
    old_ct.save(force_update=True)


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0031_auto_20200731_1022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statement', '0005_statemenetqualificationdocument'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='StatementETI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_meeting', models.DateField(blank=True, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('date_end_meeting', models.DateField(null=True)),
                ('is_continue', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.NTZ')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.RunPython(update_content_type)
    ]