# Generated by Django 2.2 on 2020-08-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0007_statementsailorpassport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailorstatementdkk',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='statemenetqualificationdocument',
            name='responsible',
        ),
    ]
