# Generated by Django 2.2 on 2020-08-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0008_auto_20200811_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemenetqualificationdocument',
            name='protocol_dkk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
