# Generated by Django 2.2 on 2020-08-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0009_auto_20200811_1808'),
        ('document', '0006_protocoldkk')
    ]

    operations = [
        migrations.AlterField(
            model_name='statemenetqualificationdocument',
            name='protocol_dkk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.ProtocolDKK'),
        ),
    ]
