# Generated by Django 2.2 on 2020-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0010_auto_20200811_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemenetqualificationdocument',
            name='protocol_dkk',
            field=models.IntegerField(null=True),
        ),
    ]
