# Generated by Django 2.2 on 2020-08-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0011_auto_20200822_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemenetqualificationdocument',
            name='protocol_dkk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to='document.ProtocolSQC'),
        ),
    ]
