# Generated by Django 3.1 on 2020-08-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0012_auto_20200822_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsailorpassport',
            name='fast_obtaining',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statementsailorpassport',
            name='is_payed_blank',
            field=models.BooleanField(default=False),
        ),
    ]
