# Generated by Django 3.1 on 2020-09-14 09:12

from django.db import migrations, models


def set_value_type_receipt(apps, schema_editor):
    StatementSailorPassport = apps.get_model("statement", "StatementSailorPassport")
    for statement in StatementSailorPassport.objects.all():
        statement.type_receipt = 4 if statement.is_continue else 2
        statement.save()


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0013_auto_20200829_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsailorpassport',
            name='type_receipt',
            field=models.IntegerField(
                choices=[(1, 'Потрібна, за 20 днів'), (2, 'Потрібна за 7 днів'), (3, 'Подовження за 20 днів'),
                         (4, 'Подовження за 7 днів')], null=True),
        ),
        migrations.RunPython(set_value_type_receipt),
    ]
