# Generated by Django 3.1 on 2020-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0014_statementsailorpassport_type_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementsailorpassport',
            name='type_receipt',
            field=models.IntegerField(choices=[(1, 'Потрібна за 20 днів'), (2, 'Потрібна за 7 днів'), (3, 'Подовження за 20 днів'), (4, 'Подовження за 7 днів')], null=True),
        ),
    ]
