# Generated by Django 3.1 on 2020-10-10 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0016_sailorstatementdkk_is_etransport_pay'),
        ('docs', '0018_auto_20201010_1147'),
        ('document', '0024_auto_20201010_1147')
    ]

    operations = [
        migrations.RenameModel('SailorStatementDKK', 'StatementSQC'),
        migrations.RunSQL('alter table statement_sailorstatementdkk_related_docs '
                          'rename to statement_statementsqc_related_docs;')
    ]
