# Generated by Django 3.1 on 2020-10-10 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0046_ntz_can_pay_platon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0030_auto_20201010_1315'),
        ('docs', '0021_auto_20201010_1308'),
        ('statement', '0017_auto_20201010_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatemenetQualificationDocument',
            new_name='StatementQualification',
        ),
        migrations.RunSQL('alter table statement_statemenetqualificationdocument_related_docs'
                          ' rename to statement_statementqualification_related_docs;')
    ]
