# Generated by Django 3.1 on 2020-10-12 13:57

from django.db import migrations
import django.contrib.contenttypes.management


def move_status_sailor_passport(apps, schema_editor):
    app = apps.get_app_config('statement')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    SailorPassport = apps.get_model('sailor', 'SailorPassport')
    SailorPassport.objects.filter(status_document_id=1).update(status_document_id=18)
    SailorPassport.objects.filter(status_document_id=2).update(status_document_id=19)
    SailorPassport.objects.filter(status_document_id=13).update(status_document_id=37)
    SailorPassport.objects.filter(status_document_id=14).update(status_document_id=21)
    SailorPassport.objects.filter(status_document_id=6).update(status_document_id=17)


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0018_auto_20201010_1317'),
    ]

    operations = [
        migrations.RunPython(move_status_sailor_passport)
    ]
