# Generated by Django 3.1 on 2020-10-22 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0019_auto_20201012_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementservicerecord',
            old_name='date_modified',
            new_name='modified_at',
        ),
    ]
