# Generated by Django 3.1 on 2020-10-22 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0020_auto_20201022_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementservicerecord',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
