# Generated by Django 3.1 on 2020-10-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0021_auto_20201022_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementservicerecord',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
