# Generated by Django 3.1 on 2020-10-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0023_auto_20201022_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementadvancedtraining',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='statementadvancedtraining',
            old_name='date_modified',
            new_name='modified_at',
        ),
    ]
