# Generated by Django 3.1 on 2020-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0027_auto_20201022_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementsqc',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='statementsqc',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
