# Generated by Django 3.1 on 2020-10-22 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0030_auto_20201022_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementeti',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
