# Generated by Django 3.1 on 2020-10-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0031_auto_20201022_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementeti',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='statementeti',
            old_name='date_modified',
            new_name='modified_at',
        ),
    ]
