# Generated by Django 3.1 on 2020-10-22 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0032_auto_20201022_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementsailorpassport',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
