# Generated by Django 3.1 on 2020-11-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0036_auto_20201030_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementadvancedtraining',
            options={'ordering': ['-created_at', '-modified_at'], 'verbose_name': 'Заява на свідоцтво про підвищення кваліфікації'},
        ),
        migrations.AlterModelOptions(
            name='statementeti',
            options={'ordering': ['-created_at', '-modified_at'], 'verbose_name': 'Заява на НТЗ'},
        ),
        migrations.AlterModelOptions(
            name='statementmedicalcertificate',
            options={'ordering': ['-created_at', '-modified_at'], 'verbose_name': 'Заява на медичне свідоцтво'},
        ),
    ]
