# Generated by Django 3.1 on 2020-11-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0037_auto_20201105_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementeti',
            options={'ordering': ['-created_at', '-modified_at'], 'permissions': (('readReportApplicationETI', 'Просмотр отчета по заявлениям НТЗ'),), 'verbose_name': 'Заява на НТЗ'},
        ),
    ]
