# Generated by Django 3.1.1 on 2020-11-19 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0038_auto_20201110_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementeti',
            options={'ordering': ['-created_at', '-modified_at'], 'permissions': (
            ('readReportApplicationETI', 'Просмотр отчета по заявлениям НТЗ'),
            ('readPaymentsETI', 'Просмотр информации по оплате заявлениий НТЗ')), 'verbose_name': 'Заява на НТЗ'},
        ),
    ]
