# Generated by Django 3.1.1 on 2020-12-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0039_auto_20201119_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementsqc',
            options={'permissions': (('writeApplicationSQCStatusRejected', 'Can change status statemnt SQC on "Rejected"'),)},
        ),
    ]
