# Generated by Django 3.1.1 on 2020-12-07 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0040_auto_20201202_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementadvancedtraining',
            options={'ordering': ['-created_at', '-modified_at'], 'permissions': (
            ('createAdvancedTraining', 'Создание документа СПК из заявления СПК'),
            ('readReportApplicationATC', 'Просмотр отчета по заявлениям КПК')),
                     'verbose_name': 'Заява на свідоцтво про підвищення кваліфікації'},
        ),
    ]
