# Generated by Django 3.1.1 on 2020-09-10 21:51

from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IORequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='b[]', max_length=250)),
                ('datetime_io', models.DateTimeField(null=True)),
                ('number', models.IntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='b[]', max_length=250)),
                ('name', models.CharField(default='', max_length=255)),
                ('imo_number', models.IntegerField(unique=True)),
                ('gross_tonnage', models.FloatField(default=0)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.flag')),
                ('type_vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.typevessel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
