# Generated by Django 3.1.1 on 2020-09-10 21:55

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iorequest',
            name='_photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='_photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250),
        ),
    ]
