# Generated by Django 3.1.1 on 2020-09-11 09:18

from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_staffposition'),
        ('ship', '0002_auto_20200910_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('full_name', models.CharField(default='', max_length=500)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.staffposition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
