# Generated by Django 3.1.1 on 2020-09-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_shipstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
