# Generated by Django 3.1.1 on 2020-09-14 14:32

from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20200914_1432'),
        ('ship', '0004_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='port',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.port'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IOShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.port')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
