# Generated by Django 3.1.1 on 2020-09-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0005_auto_20200914_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ioship',
            old_name='date_end',
            new_name='datetime_departure',
        ),
        migrations.RenameField(
            model_name='ioship',
            old_name='date_start',
            new_name='datetime_issued',
        ),
        migrations.AddField(
            model_name='ioship',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ioship',
            name='type',
            field=models.CharField(choices=[('input', 'input'), ('output', 'output')], default='input', max_length=20),
        ),
    ]
