# Generated by Django 3.1.1 on 2020-09-24 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0006_auto_20200924_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iorequest',
            name='datetime_io',
        ),
        migrations.RemoveField(
            model_name='iorequest',
            name='issued_at',
        ),
        migrations.AddField(
            model_name='iorequest',
            name='cargo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='datetime_departure',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='datetime_issued',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='next_port',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='ship_staff',
            field=models.ManyToManyField(related_name='ships', to='ship.ShipStaff'),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='type',
            field=models.CharField(choices=[('input', 'input'), ('output', 'output')], default='output', max_length=20),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipstaff',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shipstaff',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
