# Generated by Django 3.1.1 on 2020-09-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_statusdocument'),
        ('ship', '0007_auto_20200924_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='status_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.statusdocument'),
            preserve_default=False,
        ),
    ]
