# Generated by Django 3.1.1 on 2020-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_iorequest_status_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iorequest',
            name='datetime_departure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='iorequest',
            name='datetime_issued',
            field=models.DateTimeField(null=True),
        ),
    ]
