# Generated by Django 3.1.1 on 2020-09-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0009_auto_20200928_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iorequest',
            old_name='datetime_departure',
            new_name='datetime_io',
        ),
    ]
