# Generated by Django 3.1 on 2020-10-23 09:15

import django.utils.timezone
import pgcrypto.fields
from django.conf import settings
from django.db import migrations, models

import port_back.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0012_agency_is_disable'),
        ('ship', '0011_auto_20201008_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipAgentNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_photo', pgcrypto.fields.CharPGPSymmetricKeyField(default='[]', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ship_key', models.PositiveIntegerField()),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(default=port_back.middleware.get_current_authenticated_user,
                                            on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.port')),
                ('status_document',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.statusdocument')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                               related_name='verifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
