# Generated by Django 3.1 on 2020-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ship', '0012_shipagentnomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
