# Generated by Django 3.1.1 on 2020-10-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_agency_is_disable'),
        ('ship', '0013_maininfo_is_ban'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipInPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_key', models.PositiveIntegerField()),
                ('input_datetime', models.DateTimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.agency')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.port')),
            ],
            options={
                'unique_together': {('ship_key', 'port')},
            },
        ),
    ]
