# Generated by Django 3.1.1 on 2020-10-26 11:44

from django.db import migrations, models
import ship.models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0013_maininfo_is_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=ship.models.io_request_upload_path),
        ),
    ]
