# Generated by Django 3.1.1 on 2020-10-27 12:03

from django.db import migrations, models
import ship.models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0014_iorequest_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='pdf_with_watermark',
            field=models.FileField(null=True, upload_to=ship.models.io_request_upload_path),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='zip_archive',
            field=models.FileField(null=True, upload_to=ship.models.io_request_upload_path),
        ),
    ]
