# Generated by Django 3.1 on 2020-10-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ship', '0014_shipport'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='request_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='ship_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
