# Generated by Django 3.1.1 on 2020-10-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0015_auto_20201027_1203'),
        ('ship', '0015_auto_20201026_1413'),
    ]

    operations = [
    ]
