# Generated by Django 3.1.1 on 2020-10-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0016_merge_20201028_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iorequest',
            options={'ordering': ['-created_at', '-modified_at'], 'permissions': (('change_status_iorequest', 'Change status input/output requests'),)},
        ),
        migrations.AlterModelOptions(
            name='shipagentnomination',
            options={'ordering': ('-created_at', '-modified_at'), 'permissions': (('change_status_shipagentnomination', 'Change status agent nomination'),)},
        ),
    ]
