# Generated by Django 3.1.1 on 2020-11-02 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_country_sex'),
        ('ship', '0017_auto_20201030_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipstaff',
            name='country_birth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='staff_births', to='directory.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipstaff',
            name='date_birth',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipstaff',
            name='expiration',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipstaff',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='staff_nationality', to='directory.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipstaff',
            name='serial_passport',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='shipstaff',
            name='sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.sex'),
            preserve_default=False,
        ),
    ]
