# Generated by Django 3.1 on 2020-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ship', '0016_merge_20201028_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iorequest',
            name='price_form1',
            field=models.FloatField(default=0.0),
        ),
    ]
