# Generated by Django 3.1.1 on 2020-11-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0018_auto_20201102_1142'),
        ('ship', '0019_auto_20201028_1019'),
    ]

    operations = [
    ]
