# Generated by Django 3.1.1 on 2020-11-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ship', '0020_merge_20201103_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iorequest',
            name='datetime_issued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
