# Generated by Django 3.1.1 on 2020-11-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0014_auto_20201102_1144'),
        ('ship', '0022_auto_20201104_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipinport',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.agency'),
        ),
    ]
