# Generated by Django 3.1.1 on 2020-11-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0014_auto_20201102_1144'),
        ('ship', '0023_auto_20201104_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='next_port_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='directory.flag'),
        ),
    ]
