# Generated by Django 3.1.1 on 2020-11-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0024_auto_20201105_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftdocument',
            options={'ordering': ['-modified_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='photoindraftdocument',
            name='draft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ship.draftdocument'),
            preserve_default=False,
        ),
    ]
