# Generated by Django 3.1.1 on 2020-11-06 16:12

from django.db import migrations, models
import ship.models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0025_auto_20201105_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='new_pdf_file',
            field=models.FileField(null=True, upload_to=ship.models.io_request_upload_path),
        ),
    ]
