# Generated by Django 3.1.1 on 2020-11-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0026_iorequest_new_pdf_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IOShip',
        ),
    ]
