# Generated by Django 3.1.1 on 2020-11-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0027_delete_ioship'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='ban_comment',
            field=models.TextField(default=''),
        ),
    ]
