# Generated by Django 3.1.1 on 2020-11-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0028_maininfo_ban_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='ban_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
