# Generated by Django 3.1.1 on 2020-11-12 07:56

from django.db import migrations, models
import ship.models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0029_auto_20201111_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoindraftdocument',
            name='photo',
            field=models.FileField(storage=ship.models.DraftFileStorage(), upload_to=''),
        ),
    ]
