# Generated by Django 3.1.1 on 2020-11-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0030_auto_20201112_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iorequest',
            name='new_pdf_file',
        ),
    ]
