# Generated by Django 3.1.1 on 2020-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0031_remove_iorequest_new_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='deadweight',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
