# Generated by Django 3.1 on 2020-12-22 10:38

from django.db import migrations, models

import ship.models


class Migration(migrations.Migration):
    dependencies = [
        ('ship', '0032_iorequest_deadweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='inspection_act',
            field=models.FileField(null=True, upload_to=ship.models.io_request_upload_path),
        ),
    ]
