# Generated by Django 3.1.1 on 2020-12-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0033_iorequest_inspection_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='cifra_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
