# Generated by Django 3.1.1 on 2021-02-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ship', '0036_iorequest_towing_company'), ('ship', '0037_auto_20210129_1557')]

    dependencies = [
        ('ship', '0035_auto_20210120_1105'),
        ('directory', '0020_towingcompany_towingcompanydocs'),
        ('directory', '0021_auto_20210129_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='iorequest',
            name='tow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.tow'),
        ),
    ]
