# Generated by Django 2.2 on 2020-05-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0013_educationform_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('group', models.CharField(blank=True, max_length=250, null=True)),
                ('educ_with_dkk', models.BooleanField(default=False)),
                ('passed_educ_exam', models.BooleanField(default=False)),
                ('education_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.EducationForm')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Faculty')),
                ('name_nz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.NZ')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
        ),
    ]
