# Generated by Django 2.2 on 2020-05-18 11:15

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentid',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        ),
    ]
