# Generated by Django 2.2 on 2020-05-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadets', '0002_studentid_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='serial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]