# Generated by Django 3.1 on 2020-10-22 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadets', '0004_auto_20200604_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
