# Generated by Django 3.1 on 2020-10-28 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadets', '0006_auto_20201022_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
