# Generated by Django 2.2 on 2020-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NTZCoefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('packet_coefficient', models.FloatField()),
                ('ntz_coefficient', models.FloatField()),
                ('ntz_non_cash_percent', models.FloatField()),
                ('ntz_cash_percent', models.FloatField()),
            ],
        ),
    ]
