# Generated by Django 2.2 on 2020-06-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NTZCoefficient',
            new_name='ETICoefficient',
        ),
    ]
