# Generated by Django 2.2 on 2020-07-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_typeofaccrualrules'),
        ('back_office', '0002_auto_20200630_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_sqc', models.FloatField(default=0)),
                ('to_qd', models.FloatField(default=0)),
                ('to_sc', models.FloatField(default=0)),
                ('to_agent', models.FloatField(default=0)),
                ('to_itcs', models.FloatField(default=0)),
                ('to_medical', models.FloatField(default=0)),
                ('to_cec', models.FloatField(default=0)),
                ('to_portal', models.FloatField(default=0)),
                ('full_price', models.FloatField(default=0)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Rank')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.TypeOfAccrualRules')),
            ],
        ),
    ]
