# Generated by Django 3.0.8 on 2020-07-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_ntz_is_red'),
        ('back_office', '0003_documentprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceForPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_sqc', models.FloatField(default=0)),
                ('to_qd', models.FloatField(default=0)),
                ('to_sc', models.FloatField(default=0)),
                ('to_agent', models.FloatField(default=0)),
                ('to_itcs', models.FloatField(default=0)),
                ('to_medical', models.FloatField(default=0)),
                ('to_cec', models.FloatField(default=0)),
                ('to_portal', models.FloatField(default=0)),
                ('full_price', models.FloatField(default=0)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('type_of_form', models.CharField(choices=[('First', 'Первая'), ('Second', 'Вторая')], default='Second', max_length=30)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH')], default='USD', max_length=30)),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.TypeOfAccrualRules')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentPrice',
        ),
    ]
