# Generated by Django 3.0.8 on 2020-07-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_ntz_is_red'),
        ('back_office', '0004_auto_20200706_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceforposition',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH')], default='USD', max_length=30, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='full_price',
            field=models.FloatField(default=0, verbose_name='Полная цена'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='to_agent',
            field=models.FloatField(default=0, verbose_name='Агенту'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='to_cec',
            field=models.FloatField(default=0, verbose_name='В КПК'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='to_itcs',
            field=models.FloatField(default=0, verbose_name='В ИПДМ'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='to_medical',
            field=models.FloatField(default=0, verbose_name='В медицинское учереждение'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='to_portal',
            field=models.FloatField(default=0, verbose_name='В портал'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='to_qd',
            field=models.FloatField(default=0, verbose_name='В ДПВ'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='to_sc',
            field=models.FloatField(default=0, verbose_name='В сервисный центр'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='to_sqc',
            field=models.FloatField(default=0, verbose_name='В ДКК'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.TypeOfAccrualRules', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='type_of_form',
            field=models.CharField(choices=[('First', 'Первая'), ('Second', 'Вторая')], default='Second', max_length=30, verbose_name='Форма'),
        ),
    ]
