# Generated by Django 3.0.8 on 2020-07-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_ntz_is_red'),
        ('back_office', '0005_auto_20200706_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH')], default='USD', max_length=3)),
                ('type_of_form', models.CharField(choices=[('First', 'Первая'), ('Second', 'Вторая')], default='Second', max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Course')),
            ],
        ),
    ]
