# Generated by Django 3.0.8 on 2020-07-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0006_courseprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETIProfitPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_of_eti', models.FloatField()),
                ('percent_of_profit', models.FloatField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
