# Generated by Django 3.0.8 on 2020-07-08 15:24

import django.db.models.deletion
import gm2m
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directory', '0025_nz_is_red'),
        ('back_office', '0007_etiprofitpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_form1', models.FloatField(default=0.0)),
                ('payment_form2', models.FloatField(default=0.0)),
                ('item_id', models.PositiveIntegerField()),
                ('item_ct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='etiprofitpart',
            name='percent_of_eti',
            field=models.FloatField(verbose_name='Процент НТЗ'),
        ),
        migrations.AlterField(
            model_name='etiprofitpart',
            name='percent_of_profit',
            field=models.FloatField(verbose_name='Процент прибыли'),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price', to='directory.TypeOfAccrualRules', verbose_name='Тип документа'),
        ),
        migrations.CreateModel(
            name='PocketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('sailor_id', models.IntegerField()),
                ('is_payed', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(null=True)),
                ('position_type',
                 models.CharField(choices=[('start', 'Присвоєння'), ('continue', 'Подовження')], default='start',
                                  max_length=30)),
                ('full_price_form1', models.FloatField(null=True)),
                ('full_price_form2', models.FloatField(null=True)),
                ('dependencies', gm2m.fields.GM2MField(through='back_office.DependencyItem',
                                                       through_fields=['pocket_item', 'item', 'item_ct', 'item_id'])),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Position')),
            ],
        ),
        migrations.AddField(
            model_name='dependencyitem',
            name='pocket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.PocketItem'),
        ),
        migrations.AddField(
            model_name='dependencyitem',
            name='type_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependency', to='directory.TypeOfAccrualRules'),
        ),
    ]
