# Generated by Django 3.0.8 on 2020-07-09 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0025_nz_is_red'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('back_office', '0008_auto_20200708_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencyitem',
            name='item_status',
            field=models.CharField(choices=[('Was be', 'Sailor have a item before'), ('To buy', 'Sailor must a buy item'), ('Was bought', 'Sailor was bought item')], default='Was be', max_length=10),
        ),
        migrations.AddField(
            model_name='pocketitem',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pocketitem',
            name='service_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.BranchOffice'),
        ),
        migrations.AlterField(
            model_name='dependencyitem',
            name='item_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='dependencyitem',
            name='item_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='pocketitem',
            name='position',
        ),
        migrations.AddField(
            model_name='pocketitem',
            name='position',
            field=models.ManyToManyField(to='directory.Position'),
        ),
    ]
