# Generated by Django 3.0.8 on 2020-07-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0009_auto_20200709_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocketitem',
            name='sailor_id',
        ),
    ]
