# Generated by Django 3.0.8 on 2020-07-09 12:58

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0010_remove_pocketitem_sailor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocketitem',
            name='sailor_id',
            field=pgcrypto.fields.IntegerPGPSymmetricKeyField(),
            preserve_default=False,
        ),
    ]
