# Generated by Django 3.0.8 on 2020-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0011_pocketitem_sailor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketitem',
            name='position_type',
            field=models.IntegerField(choices=[(0, 'Присвоєння'), (1, 'Подовження'), (2, 'Подовження з новою должностю')], default=0, max_length=30),
        ),
    ]
