# Generated by Django 3.0.8 on 2020-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0012_auto_20200709_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pocketitem',
            name='position_type',
            field=models.IntegerField(choices=[(0, 'Присвоєння'), (1, 'Подовження'), (2, 'Подовження з новою должностю')], default=0),
        ),
        migrations.AlterField(
            model_name='pocketitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
