# Generated by Django 3.0.8 on 2020-07-11 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0025_nz_is_red'),
        ('back_office', '0013_auto_20200709_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sailor_id', pgcrypto.fields.IntegerPGPSymmetricKeyField()),
                ('is_payed', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(null=True)),
                ('position_type', models.IntegerField(choices=[(0, 'Присвоєння'), (1, 'Подовження'), (2, 'Подовження з новою должностю')], default=0)),
                ('full_price_form1', models.FloatField(null=True)),
                ('full_price_form2', models.FloatField(null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ManyToManyField(to='directory.Position')),
                ('service_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.BranchOffice')),
            ],
        ),
        migrations.AlterField(
            model_name='dependencyitem',
            name='pocket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.PacketItem'),
        ),
        migrations.DeleteModel(
            name='PocketItem',
        ),
    ]
