# Generated by Django 3.0.8 on 2020-07-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0014_auto_20200711_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencyitem',
            old_name='pocket_item',
            new_name='packet_item',
        ),
    ]
