# Generated by Django 3.0.8 on 2020-07-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0015_auto_20200711_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencyitem',
            name='packet_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='back_office.PacketItem'),
        ),
    ]
