# Generated by Django 3.0.8 on 2020-07-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0026_remove_course_price'),
        ('back_office', '0016_auto_20200711_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETIMonthRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_amount', models.FloatField()),
                ('ratio', models.FloatField(null=True)),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('ntz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntz_ratio', to='directory.NTZ')),
            ],
        ),
    ]
