# Generated by Django 3.0.8 on 2020-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0017_ntzmonthratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencyitem',
            old_name='item_ct',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='dependencyitem',
            old_name='item_id',
            new_name='object_id',
        ),
        migrations.AddField(
            model_name='dependencyitem',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
