# Generated by Django 3.0.8 on 2020-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0018_auto_20200716_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetitem',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
