# Generated by Django 3.0.8 on 2020-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0019_packetitem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetitem',
            name='include_sailor_passport',
            field=models.IntegerField(choices=[(0, 'Не потрібна'), (1, 'Потрібна, за 20 днів'), (2, 'Потрібна за 7 днів')], default=0),
        ),
    ]
