# Generated by Django 3.0.8 on 2020-07-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0020_packetitem_include_sailor_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceforposition',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='priceforposition',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH'), ('%', '%')], default='USD', max_length=30, verbose_name='Валюта'),
        ),
    ]
