# Generated by Django 3.0.8 on 2020-07-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0021_auto_20200716_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceforposition',
            name='to_td',
            field=models.FloatField(default=0, verbose_name='В Казначейство'),
        ),
    ]
