# Generated by Django 2.2 on 2020-07-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_auto_20200721_1841'),
        ('back_office', '0022_priceforposition_to_td'),
    ]

    operations = [
        migrations.AddField(
            model_name='etimonthratio',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ntz_ratio', to='directory.Course'),
            preserve_default=False,
        ),
    ]
