# Generated by Django 2.2 on 2020-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0023_etimonthratio_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetitem',
            name='date_end_meeting',
            field=models.DateField(null=True),
        ),
    ]
