# Generated by Django 2.2 on 2020-07-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0024_packetitem_date_end_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencyitem',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
