# Generated by Django 2.2 on 2020-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0025_dependencyitem_is_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencyitem',
            name='is_rated',
        ),
        migrations.AddField(
            model_name='packetitem',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
