# Generated by Django 2.2 on 2020-07-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0026_auto_20200731_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetitem',
            name='date_start_meeting',
            field=models.DateField(null=True),
        ),
    ]
