# Generated by Django 2.2 on 2020-08-20 14:06

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0027_packetitem_date_start_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetitem',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        ),
    ]
