# Generated by Django 3.1 on 2020-08-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0028_packetitem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetitem',
            name='position_type',
            field=models.IntegerField(choices=[(-1, 'Отримання документів'), (0, 'Присвоєння'), (1, 'Подовження'),
                                               (2, 'Подовження з новою должностю')], default=0),
        ),
    ]
