# Generated by Django 3.1 on 2020-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0029_auto_20200829_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetitem',
            name='include_sailor_passport',
            field=models.IntegerField(choices=[(0, 'Не потрібна'), (1, 'Потрібна, за 20 днів'), (2, 'Потрібна за 7 днів'), (3, 'Подовження за 20 днів'), (4, 'Подовження за 7 днів')], default=0),
        ),
    ]
