# Generated by Django 3.1 on 2020-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0030_auto_20200917_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencyitem',
            name='is_etransport_pay',
            field=models.BooleanField(default=False),
        ),
    ]
