# Generated by Django 3.1 on 2020-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0031_dependencyitem_is_etransport_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceforposition',
            name='to_mrc',
            field=models.FloatField(default=0, verbose_name='В морречсервис'),
        ),
    ]
