# Generated by Django 3.1.1 on 2020-11-19 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0032_priceforposition_to_mrc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencyitem',
            options={'permissions': (('readPaymentsSC', 'Просмотр информации по оплате сервисным центрам'),)},
        ),
    ]
