# Generated by Django 3.1 on 2020-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0033_auto_20201119_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetitem',
            name='education_with_sqc',
            field=models.BooleanField(default=False),
        ),
    ]
