# Generated by Django 3.1 on 2020-12-01 16:11
from datetime import date

from django.db import migrations


def add_accrual_rules(apps, schema_editor):
    app = apps.get_app_config('back_office')
    app.models_module = app.models_module or True
    TypeOfAccrualRules = apps.get_model('directory', 'TypeOfAccrualRules')
    TypeOfAccrualRules.objects.create(value='Протокол ДКК - кадет', type_sailor=1)
    TypeOfAccrualRules.objects.create(value='Кваліфікаційний документ - кадет', type_sailor=1,
                                      document_type=['Диплом', 'Танкерист', 'Свідоцтво фахівця'])
    TypeOfAccrualRules.objects.create(value='Підтвердження кваліфікаційного документу - кадет', type_sailor=1,
                                      document_type=['Підтвердження робочого диплому'])
    TypeOfAccrualRules.objects.create(value='Агент - кадет', type_sailor=1)


def add_price_for_position(apps, schema_editor):
    app = apps.get_app_config('back_office')
    app.models_module = app.models_module or True
    TypeOfAccrualRules = apps.get_model('directory', 'TypeOfAccrualRules')

    PriceForPosition = apps.get_model('back_office', 'PriceForPosition')
    sqc = TypeOfAccrualRules.objects.get(value='Протокол ДКК - кадет', type_sailor=1)
    qualification_document = TypeOfAccrualRules.objects.get(value='Кваліфікаційний документ - кадет', type_sailor=1)
    proof_of_diploma = TypeOfAccrualRules.objects.get(
        value='Підтвердження кваліфікаційного документу - кадет', type_sailor=1
    )
    agent = TypeOfAccrualRules.objects.get(value='Агент - кадет', type_sailor=1)
    today = date.today()
    PriceForPosition.objects.create(type_document=sqc, date_start=today, full_price=250)
    PriceForPosition.objects.create(type_document=sqc,
                                    date_start=today,
                                    full_price=0,
                                    is_hidden=True,
                                    type_of_form='First')
    PriceForPosition.objects.create(type_document=qualification_document, date_start=today, full_price=0)
    PriceForPosition.objects.create(
        type_document=qualification_document,
        date_start=today,
        full_price=0,
        type_of_form='First',
        is_hidden=True
    )
    PriceForPosition.objects.create(type_document=proof_of_diploma, date_start=today, full_price=0)
    PriceForPosition.objects.create(
        type_document=proof_of_diploma,
        date_start=today,
        full_price=0,
        type_of_form='First',
        is_hidden=True,
    )
    PriceForPosition.objects.create(type_document=agent, date_start=today, full_price=60)
    PriceForPosition.objects.create(
        type_document=agent,
        date_start=today,
        full_price=60,
        type_of_form='First',
        is_hidden=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ('back_office', '0034_auto_20201201_1745'),
        ('directory', '0056_typeofaccrualrules_type_sailor'),
    ]

    operations = [
        migrations.RunPython(add_accrual_rules),
        migrations.RunPython(add_price_for_position),
    ]
