# Generated by Django 3.1 on 2021-01-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('secretary_sqc', 'ITCS secretary'), ('commissioner', 'Commissioner SQC'), ('verifier', 'Verifier'), ('agent', 'Agent'), ('sailor', 'Sailor'), ('medical', 'Medical'), ('secretary_education', 'Secretary of education institution'), ('head_agent', 'Head of agents'), ('secretary_service', 'Service center secretary'), ('registry', 'Registry'), ('dpd', 'DPD'), ('back_office', 'Back office'), ('marad', 'Morrichservice'), ('eti_employee', 'ETI employee'), ('secretary_atc', 'Secretary of ATC')], default='sailor', max_length=50),
        ),
    ]
