# Generated by Django 3.1.1 on 2020-11-12 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('directory', '0054_auto_20201104_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableExamsToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_meeting', models.DateTimeField()),
                ('datetime_end_meeting', models.DateTimeField()),
                ('list_positions',
                 django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
    ]
