# Generated by Django 2.2 on 2020-07-27 11:15

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspBranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_branch', models.CharField(max_length=7)),
                ('code_track_record', models.CharField(blank=True, max_length=7, null=True)),
                ('name_ukr', models.CharField(max_length=150)),
                ('name_eng', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('house_num', models.CharField(max_length=15)),
                ('index', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('FIO_director', models.CharField(blank=True, max_length=150, null=True)),
                ('is_disable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspCommitte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('FIO_main', models.CharField(max_length=150)),
                ('FIO_secretary', models.CharField(blank=True, max_length=150, null=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('branch_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.InspBranchOffice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_ukr', models.TextField()),
                ('value_eng', models.TextField()),
                ('value_abbr', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
                ('is_disable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_port', models.CharField(max_length=7)),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('position_capitan_ukr', models.TextField()),
                ('position_capitan_eng', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_disable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_dkk', models.BooleanField(default=True)),
                ('team', models.CharField(blank=True, max_length=200, null=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('experience_description', models.TextField(blank=True, null=True)),
                ('standarts_text', models.TextField(blank=True, null=True)),
                ('level', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='inspection.InspLevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspProtocolDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ukr', models.CharField(max_length=255)),
                ('last_name_ukr', models.CharField(max_length=255)),
                ('middle_name_ukr', models.CharField(default='', max_length=255)),
                ('first_name_eng', models.CharField(max_length=255)),
                ('last_name_eng', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('integration_id', models.IntegerField()),
                ('statement_dkk', models.CharField(max_length=255)),
                ('number_document', models.IntegerField()),
                ('date_meeting', models.DateField(blank=True, null=True)),
                ('commisioners', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('function_limitation', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('branch_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.InspBranchOffice')),
                ('committe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.InspCommitte')),
                ('decision', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='inspection.InspDecision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('is_disable', models.BooleanField(default=False)),
                ('summ', models.FloatField(blank=True, null=True)),
                ('is_dkk', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=255, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspDirection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspStatusDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=150)),
                ('name_eng', models.CharField(max_length=150)),
                ('for_service', models.CharField(max_length=200)),
                ('is_disable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspTypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.TextField()),
                ('name_eng', models.TextField()),
                ('code', models.IntegerField()),
                ('for_service', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('summ', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspTypeRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspStatementServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ukr', models.CharField(max_length=255)),
                ('last_name_ukr', models.CharField(max_length=255)),
                ('middle_name_ukr', models.CharField(default='', max_length=255)),
                ('first_name_eng', models.CharField(max_length=255)),
                ('last_name_eng', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('integration_id', models.IntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspStatusDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspStatementQualificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ukr', models.CharField(max_length=255)),
                ('last_name_ukr', models.CharField(max_length=255)),
                ('middle_name_ukr', models.CharField(default='', max_length=255)),
                ('first_name_eng', models.CharField(max_length=255)),
                ('last_name_eng', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('integration_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('list_positions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('is_continue', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspPort')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspPosition')),
                ('protocol_dkk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection.InspProtocolDKK')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inspection.InspRank')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspStatusDocument')),
                ('type_document', models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspTypeDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspServiceRecordSailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ukr', models.CharField(max_length=255)),
                ('last_name_ukr', models.CharField(max_length=255)),
                ('middle_name_ukr', models.CharField(default='', max_length=255)),
                ('first_name_eng', models.CharField(max_length=255)),
                ('last_name_eng', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('integration_id', models.IntegerField()),
                ('number', models.BigIntegerField()),
                ('issued_by', models.TextField()),
                ('auth_agent_ukr', models.CharField(max_length=200)),
                ('auth_agent_eng', models.CharField(max_length=200)),
                ('date_issued', models.DateField()),
                ('blank_strict_report', models.BigIntegerField(blank=True, null=True)),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspBranchOffice')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspStatusDocument')),
            ],
            options={
                'verbose_name': 'Послужна книжка моряка',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspSailorStatementDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ukr', models.CharField(max_length=255)),
                ('last_name_ukr', models.CharField(max_length=255)),
                ('middle_name_ukr', models.CharField(default='', max_length=255)),
                ('first_name_eng', models.CharField(max_length=255)),
                ('last_name_eng', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('integration_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('is_payed', models.BooleanField(default=False)),
                ('list_positions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('is_continue', models.IntegerField(default=0)),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspBranchOffice')),
                ('on_create_rank', models.ManyToManyField(related_name='on_create_rank', to='inspection.InspRank')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspRank')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspStatusDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspSailorPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ukr', models.CharField(max_length=255)),
                ('last_name_ukr', models.CharField(max_length=255)),
                ('middle_name_ukr', models.CharField(default='', max_length=255)),
                ('first_name_eng', models.CharField(max_length=255)),
                ('last_name_eng', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('integration_id', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('number_document', models.CharField(max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('other_port', models.CharField(blank=True, max_length=250, null=True)),
                ('captain', models.CharField(max_length=255)),
                ('date_renewal', models.DateField(blank=True, null=True)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection.InspPort')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspStatusDocument')),
            ],
            options={
                'verbose_name': 'Посвідчення особи моряка',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insprank',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspTypeDocument'),
        ),
        migrations.AddField(
            model_name='insprank',
            name='type_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspTypeRank'),
        ),
        migrations.CreateModel(
            name='InspQualificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ukr', models.CharField(max_length=255)),
                ('last_name_ukr', models.CharField(max_length=255)),
                ('middle_name_ukr', models.CharField(default='', max_length=255)),
                ('first_name_eng', models.CharField(max_length=255)),
                ('last_name_eng', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('integration_id', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('number_document', models.BigIntegerField(blank=True, null=True)),
                ('other_number', models.CharField(blank=True, max_length=50, null=True)),
                ('list_positions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('other_port', models.CharField(blank=True, max_length=250, null=True)),
                ('fio_captain_ukr', models.CharField(blank=True, max_length=200, null=True)),
                ('fio_captain_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('new_document', models.BooleanField(default=True)),
                ('function_limitation', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('strict_blank', models.CharField(blank=True, max_length=30, null=True)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection.InspPort')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inspection.InspRank')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection.InspStatementQualificationDocument')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspStatusDocument')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspTypeDocument')),
            ],
            options={
                'verbose_name': 'Кваліфікаційний документ',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inspprotocoldkk',
            name='status_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspStatusDocument'),
        ),
        migrations.AddField(
            model_name='inspposition',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection.InspRank'),
        ),
        migrations.AddField(
            model_name='inspcommitte',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.InspDirection'),
        ),
        migrations.CreateModel(
            name='InspCommisioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('committe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.InspCommitte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
