# Generated by Django 2.2 on 2020-07-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspprotocoldkk',
            name='integration_id',
        ),
        migrations.RemoveField(
            model_name='inspqualificationdocument',
            name='integration_id',
        ),
        migrations.RemoveField(
            model_name='inspsailorpassport',
            name='integration_id',
        ),
        migrations.RemoveField(
            model_name='inspsailorstatementdkk',
            name='integration_id',
        ),
        migrations.RemoveField(
            model_name='inspservicerecordsailor',
            name='integration_id',
        ),
        migrations.RemoveField(
            model_name='inspstatementqualificationdocument',
            name='integration_id',
        ),
        migrations.RemoveField(
            model_name='inspstatementqualificationdocument',
            name='position',
        ),
        migrations.RemoveField(
            model_name='inspstatementservicerecord',
            name='integration_id',
        ),
        migrations.AlterField(
            model_name='inspprotocoldkk',
            name='statement_dkk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspSailorStatementDKK'),
        ),
    ]
