# Generated by Django 2.2 on 2020-07-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20200727_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InspStatementServiceRecord',
        ),
    ]
