# Generated by Django 2.2 on 2020-08-08 14:52

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_delete_inspstatementservicerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ukr', models.CharField(max_length=200)),
                ('first_name_eng', models.CharField(max_length=200)),
                ('last_name_ukr', models.CharField(max_length=200)),
                ('last_name_eng', models.CharField(max_length=200)),
                ('middle_name_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name_ukr', models.CharField(max_length=200)),
                ('date_birth', pgcrypto.fields.DatePGPSymmetricKeyField()),
                ('sex', models.IntegerField(default=0)),
                ('contact_info', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='inspprotocoldkk',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='inspprotocoldkk',
            name='first_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspprotocoldkk',
            name='first_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspprotocoldkk',
            name='last_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspprotocoldkk',
            name='last_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspprotocoldkk',
            name='middle_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspqualificationdocument',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='inspqualificationdocument',
            name='first_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspqualificationdocument',
            name='first_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspqualificationdocument',
            name='last_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspqualificationdocument',
            name='last_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspqualificationdocument',
            name='middle_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspsailorpassport',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='inspsailorpassport',
            name='first_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspsailorpassport',
            name='first_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspsailorpassport',
            name='last_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspsailorpassport',
            name='last_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspsailorpassport',
            name='middle_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspsailorstatementdkk',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='inspsailorstatementdkk',
            name='first_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspsailorstatementdkk',
            name='first_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspsailorstatementdkk',
            name='last_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspsailorstatementdkk',
            name='last_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspsailorstatementdkk',
            name='middle_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspservicerecordsailor',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='inspservicerecordsailor',
            name='first_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspservicerecordsailor',
            name='first_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspservicerecordsailor',
            name='last_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspservicerecordsailor',
            name='last_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspservicerecordsailor',
            name='middle_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspstatementqualificationdocument',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='inspstatementqualificationdocument',
            name='first_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspstatementqualificationdocument',
            name='first_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspstatementqualificationdocument',
            name='last_name_eng',
        ),
        migrations.RemoveField(
            model_name='inspstatementqualificationdocument',
            name='last_name_ukr',
        ),
        migrations.RemoveField(
            model_name='inspstatementqualificationdocument',
            name='middle_name_ukr',
        ),
    ]
