# Generated by Django 2.2 on 2020-08-08 15:19

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_auto_20200808_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspprofile',
            name='date_birth',
            field=pgcrypto.fields.DatePGPSymmetricKeyField(null=True),
        ),
    ]
