# Generated by Django 2.2 on 2020-08-22 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inspection', '0005_auto_20200808_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspservicerecordsailor',
            old_name='status',
            new_name='status_document',
        ),
    ]
