# Generated by Django 3.1 on 2020-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inspection', '0006_auto_20200822_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspprotocoldkk',
            name='function_limitation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspqualificationdocument',
            name='function_limitation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
