# Generated by Django 3.1 on 2020-10-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_auto_20200826_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspprotocoldkk',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='inspsailorstatementdkk',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='inspstatementqualificationdocument',
            old_name='date_create',
            new_name='created_at',
        ),
    ]
