# Generated by Django 3.1 on 2020-09-23 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatonPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('send_time', models.DateTimeField()),
                ('order', models.CharField(default='', max_length=50)),
                ('platon_id', models.CharField(default='', max_length=50)),
                ('amount', models.FloatField()),
                ('description', models.TextField(default='')),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('pay_time', models.DateTimeField(null=True)),
                ('pan_mask', models.CharField(default='', max_length=16)),
                ('status', models.CharField(default='', max_length=15)),
                ('sum_distribution', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='contenttypes.contenttype')),
            ],
        ),
    ]
