# Generated by Django 2.2 on 2020-01-18 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sailor', '0009_auto_20200118_0956'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0002_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsForStatementServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('num_blank', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.ServiceRecordSailor')),
            ],
        ),
        migrations.CreateModel(
            name='DocsForStatementQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.StatemenetQualificationDocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocsForStatementDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.SailorStatementDKK')),
            ],
        ),
        migrations.CreateModel(
            name='DocsForServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.ServiceRecordSailor')),
            ],
        ),
        migrations.CreateModel(
            name='DocsForProtocolDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.ProtocolDKK')),
            ],
        ),
    ]
