# Generated by Django 2.2 on 2020-01-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0009_auto_20200118_0956'),
        ('directory', '0002_decision'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocForQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('is_proof_diploma', models.BooleanField(default=False)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='DocsForQualificationDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.QualitifcationDocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocsForProofOfDiplomaDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.ProofOfWorkDiploma')),
            ],
        ),
    ]
