# Generated by Django 2.2 on 2020-08-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_docsforstatementdkk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforstatementdkk',
            name='statement',
            field=models.IntegerField(),
        ),
    ]
