# Generated by Django 2.2 on 2020-08-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20200808_1430'),
        ('statement', '0004_sailorstatementdkk')
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforstatementdkk',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.SailorStatementDKK'),
        ),
    ]
