# Generated by Django 2.2 on 2020-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20200808_1442'),

    ]

    operations = [
        migrations.AlterField(
            model_name='docsforstatementqualification',
            name='statement',
            field=models.IntegerField(),
        ),
    ]
