# Generated by Django 2.2 on 2020-08-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20200808_1632'),
        ('statement', '0005_statemenetqualificationdocument')
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforstatementqualification',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.StatemenetQualificationDocument'),
        ),
    ]
