# Generated by Django 2.2 on 2020-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20200808_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforservicerecord',
            name='service_record',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docsforstatementservicerecord',
            name='service_record',
            field=models.IntegerField(),
        ),
    ]
