# Generated by Django 2.2 on 2020-08-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20200809_1519'),
        ('document', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforservicerecord',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.ServiceRecordSailor'),
        ),
        migrations.AlterField(
            model_name='docsforstatementservicerecord',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.ServiceRecordSailor'),
        ),
    ]
