# Generated by Django 2.2 on 2020-08-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20200809_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforprotocoldkk',
            name='protocol',
            field=models.IntegerField(),
        ),
    ]
