# Generated by Django 2.2 on 2020-08-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20200811_1808'),
        ('document', '0006_protocoldkk')
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforprotocoldkk',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.ProtocolDKK'),
        ),
    ]
