# Generated by Django 2.2 on 2020-08-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20200811_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforqualificationdocuments',
            name='qualification',
            field=models.IntegerField(),
        ),
    ]
