# Generated by Django 2.2 on 2020-08-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_auto_20200814_0015'),
        ('document', '0009_qualitifcationdocument')

    ]

    operations = [
        migrations.AlterField(
            model_name='docsforqualificationdocuments',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.QualitifcationDocument'),
        ),
    ]
