# Generated by Django 2.2 on 2020-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_auto_20200814_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforproofofdiplomadocuments',
            name='proof',
            field=models.IntegerField(),
        ),
    ]
