# Generated by Django 2.2 on 2020-08-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_auto_20200814_1116'),
        ('document', '0010_proofofworkdiploma')
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforproofofdiplomadocuments',
            name='proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.ProofOfWorkDiploma'),
        ),
    ]
