# Generated by Django 2.2 on 2020-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('docs', '0015_auto_20200814_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforservicerecord',
            name='service_record',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docsforstatementservicerecord',
            name='service_record',
            field=models.IntegerField(),
        ),
    ]
