# Generated by Django 2.2 on 2020-08-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('docs', '0016_auto_20200822_1621'),
        ('document', '0014_auto_20200822_1622')
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforservicerecord',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.ServiceRecord'),
        ),
        migrations.AlterField(
            model_name='docsforstatementservicerecord',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.ServiceRecord'),
        ),
    ]
