# Generated by Django 3.1 on 2020-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('docs', '0017_auto_20200822_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforstatementdkk',
            name='statement',
            field=models.IntegerField(),
        ),
    ]
