# Generated by Django 3.1 on 2020-10-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statement', '0017_auto_20201010_1153'),
        ('docs', '0018_auto_20201010_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforstatementdkk',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statementsqc'),
        ),
    ]
