# Generated by Django 3.1 on 2020-10-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('docs', '0019_auto_20201010_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforqualificationdocuments',
            name='qualification',
            field=models.IntegerField(),
        ),
    ]
