# Generated by Django 3.1 on 2020-10-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0029_auto_20201010_1308'),
        ('docs', '0020_auto_20201010_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsforqualificationdocuments',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.qualificationdocument'),
        ),
    ]
