# Generated by Django 3.1.1 on 2020-10-16 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgcrypto.fields
import port_back.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file_signature', models.FileField(upload_to='')),
                ('is_actual', models.BooleanField(default=True)),
                ('password', pgcrypto.fields.CharPGPSymmetricKeyField(default='', max_length=255)),
                ('author', models.ForeignKey(default=port_back.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('blocked_user', models.ManyToManyField(related_name='blocked_in_signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
