# Generated by Django 3.1.1 on 2020-10-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import port_back.middleware
import signature.models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0014_iorequest_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['is_actual', '-created_at', '-modified_at']},
        ),
        migrations.AddField(
            model_name='signature',
            name='ERDPOU',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='signature',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='signature',
            name='type_signature',
            field=models.CharField(choices=[('sign', 'sign'), ('stamp', 'stamp')], default='sign', max_length=10),
        ),
        migrations.AddField(
            model_name='signature',
            name='watermark',
            field=models.FileField(blank=True, null=True, upload_to=signature.models.signature_upload_path),
        ),
        migrations.AlterField(
            model_name='signature',
            name='file_signature',
            field=models.FileField(upload_to=signature.models.signature_upload_path),
        ),
        migrations.CreateModel(
            name='IORequestSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('base64_signature', models.TextField(blank=True, default='')),
                ('file_signature', models.FileField(upload_to=signature.models.io_sign_upload_path)),
                ('author', models.ForeignKey(default=port_back.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('io_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.iorequest')),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signature.signature')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
