# Generated by Django 3.1.1 on 2020-10-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_agency_is_disable'),
        ('signature', '0002_auto_20201026_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.port'),
        ),
    ]
