# Generated by Django 3.1.1 on 2020-10-27 08:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_signature_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterCertificationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_cn', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=None)),
                ('address', models.CharField(default='', max_length=300)),
                ('oscp_address', models.CharField(default='', max_length=300)),
                ('oscp_port', models.IntegerField(null=True)),
                ('cmp_address', models.CharField(default='', max_length=300)),
                ('tsp_address', models.CharField(default='', max_length=300)),
                ('tsp_port', models.IntegerField(null=True)),
                ('direct_access', models.NullBooleanField(default=None)),
                ('qscd_SN_in_cert', models.NullBooleanField(default=None)),
                ('cmp_compatibility', models.IntegerField(null=True)),
            ],
        ),
    ]
