# Generated by Django 3.1.1 on 2020-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0004_centercertificationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centercertificationkey',
            name='direct_access',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='centercertificationkey',
            name='qscd_SN_in_cert',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
