# Generated by Django 3.1.1 on 2020-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_auto_20201027_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centercertificationkey',
            old_name='oscp_address',
            new_name='ocsp_address',
        ),
        migrations.RenameField(
            model_name='centercertificationkey',
            old_name='oscp_port',
            new_name='ocsp_port',
        ),
        migrations.AddField(
            model_name='centercertificationkey',
            name='certs_in_key',
            field=models.BooleanField(null=True),
        ),
    ]
