# Generated by Django 3.1.1 on 2020-12-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0034_iorequest_cifra_uuid'),
        ('signature', '0006_auto_20201027_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iorequestsign',
            name='io_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='ship.iorequest'),
        ),
    ]
