# Generated by Django 3.1.1 on 2020-12-31 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature', '0007_auto_20201223_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
