# Generated by Django 2.2 on 2020-02-27 12:25

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0009_regulatoryground_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('group', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('additional_data', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', 'en'), ('UA', 'ua')], default='UA', max_length=2)),
                ('branch_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.BranchOffice')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.City')),
                ('main_group', models.ManyToManyField(blank=True, to='user_profile.MainGroups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FullUserSailorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sailor_key', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(max_length=250)),
                ('action_type', models.CharField(max_length=250)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('old_obj_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('new_obj_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSailorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sailor_key', models.IntegerField()),
                ('date_open', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sailor_key')},
            },
        ),
    ]
