# Generated by Django 2.2 on 2020-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='MainGroups',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150, unique=True)),
        #         ('group', models.ManyToManyField(blank=True, to='auth.Group')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='main_group',
        #     field=models.ManyToManyField(blank=True, to='user_profile.MainGroups'),
        # ),
    ]
