# Generated by Django 2.2 on 2020-01-24 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_usersailorhistory'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='FullUserSailorHistory',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('sailor_key', models.IntegerField()),
        #         ('datetime', models.DateTimeField(auto_now_add=True)),
        #         ('module', models.CharField(max_length=250)),
        #         ('action_type', models.CharField(max_length=250)),
        #         ('object_id', models.PositiveIntegerField()),
        #         ('text', models.TextField(blank=True, null=True)),
        #         ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
