# Generated by Django 2.2 on 2020-01-25 17:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_fullusersailorhistory'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='fullusersailorhistory',
        #     name='new_obj_json',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='fullusersailorhistory',
        #     name='old_obj_json',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='fullusersailorhistory',
        #     name='object_id',
        #     field=models.PositiveIntegerField(blank=True, null=True),
        # ),
    ]
