# Generated by Django 2.2 on 2020-02-27 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200125_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('version', models.PositiveIntegerField()),
                ('v_frontend', models.PositiveIntegerField()),
                ('v_backend', models.PositiveIntegerField()),
            ],
        ),
    ]
