# Generated by Django 2.2 on 2020-04-02 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0012_rank_priority'),
        ('auth', '0011_update_proxy_permissions'),
        ('user_profile', '0006_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOfficeRestrictionForPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_office', models.ManyToManyField(to='directory.BranchOffice')),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
