# Generated by Django 2.2 on 2020-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_branchofficerestrictionforpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_commissioner',
            field=models.BooleanField(default=False),
        ),
    ]
