# Generated by Django 2.2 on 2020-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_userprofile_is_commissioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vchasno_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
