# Generated by Django 2.2 on 2020-06-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_userprofile_vchasno_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersailorhistory',
            unique_together=set(),
        ),
    ]
