# Generated by Django 2.2 on 2020-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_tochangepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='yubikey_authorization',
            field=models.BooleanField(default=False),
        ),
    ]
