# Generated by Django 2.2 on 2020-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_userprofile_yubikey_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullusersailorhistory',
            name='sailor_key',
            field=models.IntegerField(null=True),
        ),
    ]
