# Generated by Django 2.2 on 2020-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20200622_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
