# Generated by Django 2.2 on 2020-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(choices=[('secretary', 'secretary'), ('commissioner', 'commissioner'), ('agent', 'agent'), ('sailor', 'sailor')], default='secretary', max_length=50),
        ),
    ]
