# Generated by Django 3.0.8 on 2020-07-21 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_userprofile_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
