# Generated by Django 2.2 on 2020-07-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_auto_20200730_1156'),
        ('user_profile', '0017_auto_20200721_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.AgentGroup'),
        ),
    ]
