# Generated by Django 2.2 on 2020-07-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_userprofile_agent_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.UserAgentGroup'),
        ),
    ]
