# Generated by Django 2.2 on 2020-08-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0031_auto_20200731_1022'),
        ('user_profile', '0019_auto_20200730_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doctor_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.DoctrorInMedicalInstitution'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(choices=[('secretary', 'secretary'), ('commissioner', 'commissioner'), ('agent', 'agent'), ('sailor', 'sailor'), ('medical', 'medical')], default='secretary', max_length=50),
        ),
    ]
