# Generated by Django 2.2 on 2020-08-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0020_auto_20200812_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(
                choices=[('secretary', 'secretary'), ('verifier', 'verifier'), ('commissioner', 'commissioner'),
                         ('agent', 'agent'), ('sailor', 'sailor'), ('medical', 'medical')], default='secretary',
                max_length=50),
        ),
    ]
