# Generated by Django 2.2 on 2020-08-28 09:27

from django.db import migrations, models


def transfer_agent_group(apps, schema_editor):
    UserAgentGroup = apps.get_model('agent', 'UserAgentGroup')
    for user_group in UserAgentGroup.objects.all():
        groups = list(user_group.user.userprofile.agent_group.values_list('id', flat=True))
        if user_group.group.id in groups:
            continue
        if user_group.type_user == 'agent':
            user_group.user.userprofile.agent_group.add(user_group.group)
        elif user_group.type_user == 'head':
            user_group.user.userprofile.type_user = 'head_agent'
            user_group.user.userprofile.save(update_fields=['type_user'])
            user_group.user.userprofile.agent_group.add(user_group.group)
        elif user_group.type_user == 'secretary':
            user_group.user.userprofile.type_user = 'secretary_service'
            user_group.user.userprofile.save(update_fields=['type_user'])
            user_group.user.userprofile.agent_group.add(user_group.group)


class Migration(migrations.Migration):
    dependencies = [
        ('agent', '0014_auto_20200817_2302'),
        ('user_profile', '0022_auto_20200818_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='agent_group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_group',
            field=models.ManyToManyField(blank=True, to='agent.AgentGroup'),
        ),
        migrations.RunPython(transfer_agent_group),
    ]
