# Generated by Django 3.1 on 2020-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0023_auto_20200828_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullusersailorhistory',
            name='new_obj_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fullusersailorhistory',
            name='old_obj_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
