# Generated by Django 3.1 on 2020-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0024_auto_20200826_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(
                choices=[('secretary_sqc', 'secretary_sqc'), ('verifier', 'verifier'), ('commissioner', 'commissioner'),
                         ('agent', 'agent'), ('sailor', 'sailor'), ('medical', 'medical'),
                         ('secretary_education', 'secretary_education'), ('head_agent', 'head_agent'),
                         ('secretary_service', 'secretary_service'), ('registry', 'registry'), ('dpd', 'dpd'),
                         ('back_office', 'back_office'), ('marad', 'marad')], default='secretary_sqc', max_length=50),
        ),
    ]
