# Generated by Django 3.1 on 2020-10-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0050_auto_20201010_1621'),
        ('user_profile', '0025_auto_20200923_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='doctor_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.doctrorinmedicalinstitution'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vchasno_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
