# Generated by Django 3.1 on 2020-10-19 12:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_auto_20201012_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
