# Generated by Django 3.1.1 on 2020-12-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0028_userprofile_eti_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
