# Generated by Django 3.1.1 on 2020-12-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0029_userprofile_is_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='directory.nz'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(
                choices=[('secretary_sqc', 'secretary_sqc'), ('verifier', 'verifier'), ('commissioner', 'commissioner'),
                         ('agent', 'agent'), ('sailor', 'sailor'), ('medical', 'medical'),
                         ('secretary_education', 'secretary_education'), ('head_agent', 'head_agent'),
                         ('secretary_service', 'secretary_service'), ('registry', 'registry'), ('dpd', 'dpd'),
                         ('back_office', 'back_office'), ('marad', 'marad'), ('eti_employee', 'eti_employee'),
                         ('secretary_atc', 'secretary_atc')], default='secretary_sqc', max_length=50),
        ),
    ]
