# Generated by Django 2.2 on 2020-03-03 12:40

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0011_auto_20200303_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDocumentForVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('security_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatementVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('inn', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
        ),
    ]
