# Generated by Django 2.2 on 2020-03-14 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySMSSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=255)),
                ('status_answer', models.CharField(max_length=255)),
                ('id_mailing', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_code', models.CharField(blank=True, max_length=25, null=True)),
                ('date_answer', models.DateTimeField(blank=True, null=True)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
