# Generated by Django 2.2 on 2020-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0002_historysmssending'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatementverification',
            name='sailor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
