# Generated by Django 2.2 on 2020-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0003_userstatementverification_sailor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatementverification',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatementverification',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatementverification',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatementverification',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatementverification',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstatementverification',
            name='sailor_id',
            field=models.IntegerField(null=True),
        ),
    ]
