# Generated by Django 2.2 on 2020-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0004_auto_20200428_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historysmssending',
            name='distance_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historysmssending',
            name='id_mailing',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='historysmssending',
            name='message',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='historysmssending',
            name='status_answer',
            field=models.CharField(max_length=600),
        ),
    ]
