# Generated by Django 2.2 on 2020-06-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0005_auto_20200501_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorySMSSending',
            new_name='HistoryNotification',
        ),
    ]
