# Generated by Django 2.2 on 2020-06-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sms_auth', '0006_auto_20200620_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='historynotification',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='historynotification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historynotification',
            name='type',
            field=models.CharField(choices=[('Push', 'Push'), ('Phone', 'Phone'), ('Mail', 'Mail')], default='Phone', max_length=50),
        ),
    ]
