# Generated by Django 2.2 on 2020-06-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0007_auto_20200620_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historynotification',
            old_name='phone',
            new_name='destination',
        ),
    ]
