# Generated by Django 2.2 on 2020-06-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0008_auto_20200620_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historynotification',
            name='destination',
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name='historynotification',
            name='distance_code',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
