# Generated by Django 2.2 on 2020-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sms_auth', '0009_auto_20200620_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatementverification',
            name='service',
            field=models.CharField(choices=[('e-transport', 'e-transport'), ('e-sailor', 'e-sailor')],
                                   default='e-transport', max_length=20),
        ),
    ]
