# Generated by Django 3.1 on 2020-09-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sms_auth', '0010_userstatementverification_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatementverification',
            name='service',
            field=models.CharField(choices=[('e-transport', 'e-transport'), ('e-sailor', 'e-sailor'),
                                            ('morrichservice', 'morrichservice')], default='e-transport',
                                   max_length=20),
        ),
    ]
