# Generated by Django 3.1 on 2020-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0011_auto_20200925_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatementverification',
            name='service',
            field=models.CharField(choices=[('e-transport', 'e-transport'), ('e-sailor', 'e-sailor'), ('morrichservice', 'morrichservice'), ('MDU', 'MDU')], default='e-transport', max_length=20),
        ),
    ]
