# Generated by Django 3.0.8 on 2020-07-10 09:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_ntz_is_red'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_info', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.City')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
        ),
    ]
