# Generated by Django 3.0.8 on 2020-07-17 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_statementagentsailor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementagent',
            name='photo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
