# Generated by Django 2.2 on 2020-07-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agentgroups_agentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=255)),
                ('type_user', models.CharField(choices=[('agent', 'agent'), ('head', 'head'), ('verifier', 'verifier')], default='agent', max_length=15)),
                ('is_disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AgentGroups',
        ),
    ]
