# Generated by Django 2.2 on 2020-07-30 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0006_auto_20200730_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(choices=[('agent', 'agent'), ('head', 'head'), ('verifier', 'verifier')], default='agent', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='agentgroup',
            name='type_user',
        ),
        migrations.DeleteModel(
            name='AgentProfile',
        ),
        migrations.AddField(
            model_name='useragentgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent.AgentGroup'),
        ),
        migrations.AddField(
            model_name='useragentgroup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
