# Generated by Django 2.2 on 2020-07-30 10:12

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_auto_20200730_1258'),
    ]

    operations = [
    ]
