# Generated by Django 2.2 on 2020-07-30 10:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_auto_20200730_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementagent',
            name='contact_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
