# Generated by Django 2.2 on 2020-07-30 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_auto_20200730_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementagentsailor',
            name='photo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
