# Generated by Django 2.2 on 2020-07-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_statementagentsailor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementagentsailor',
            name='is_active',
        ),
    ]
