# Generated by Django 2.2 on 2020-08-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_remove_statementagentsailor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementagent',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agent.AgentGroup'),
        ),
    ]
