# Generated by Django 2.2 on 2020-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_statementagent_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementagent',
            name='serial_passport',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='statementagent',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
