# Generated by Django 2.2 on 2020-08-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agent', '0013_auto_20200807_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragentgroup',
            name='type_user',
            field=models.CharField(choices=[('agent', 'agent'), ('head', 'head'), ('secretary', 'secretary')],
                                   default='agent', max_length=15),
        ),
    ]
