# Generated by Django 3.1 on 2020-09-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agent', '0014_auto_20200817_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsailor',
            name='date_end_proxy',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='statementagentsailor',
            name='date_end_proxy',
            field=models.DateField(blank=True, null=True),
        ),
    ]
