# Generated by Django 3.1 on 2020-09-23 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('agent', '0015_auto_20200910_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAgentGroup',
        ),
    ]
