# Generated by Django 3.1 on 2020-09-30 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0016_delete_useragentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeToStatementAgentSailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.IntegerField(unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('sailor_key', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
