# Generated by Django 3.1 on 2020-10-22 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_codetostatementagentsailor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsailor',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agentsailor',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
