# Generated by Django 3.1 on 2020-10-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_auto_20201022_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentsailor',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='agentsailor',
            old_name='date_modified',
            new_name='modified_at',
        ),
    ]
