# Generated by Django 3.1 on 2020-10-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_auto_20201022_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementagentsailor',
            options={'ordering': ['-created_at', '-modified_at']},
        ),
        migrations.RenameField(
            model_name='statementagentsailor',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='statementagentsailor',
            old_name='date_modified',
            new_name='modified_at',
        ),
    ]
