# Generated by Django 3.1 on 2020-10-22 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_auto_20201022_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementagent',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statementagent',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
