# Generated by Django 3.1 on 2020-10-22 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_auto_20201022_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetostatementagentsailor',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
