# Generated by Django 3.1 on 2020-10-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0024_auto_20201022_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codetostatementagentsailor',
            options={'ordering': ['-created_at', '-modified_at']},
        ),
        migrations.RenameField(
            model_name='codetostatementagentsailor',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='codetostatementagentsailor',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
