# Generated by Django 2.2 on 2020-06-17 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yubikey_api_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(default='')),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('datetime_login', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_authorization_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
