# Generated by Django 2.2 on 2020-06-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yubikey_api_auth', '0002_authorizationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationlog',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
