# Generated by Django 2.2 on 2020-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yubikey_api_auth', '0003_authorizationlog_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationlog',
            name='address',
            field=models.TextField(default='', null=True),
        ),
    ]
