# Generated by Django 3.1 on 2020-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yubikey_api_auth', '0004_auto_20200626_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptoken',
            name='sign_req',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
