# Generated by Django 2.2 on 2020-04-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('areas_center', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NovaPoshtaCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('id_city', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.NovaPoshtaArea')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=100)),
                ('ref_description_NP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStreet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UkrPoshtaDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_courier', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('other_street', models.CharField(blank=True, max_length=200, null=True)),
                ('house', models.CharField(blank=True, max_length=20, null=True)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NovaPoshtaWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('code', models.BigIntegerField()),
                ('name_ukr', models.CharField(max_length=255)),
                ('short_address', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.NovaPoshtaCity')),
            ],
        ),
        migrations.CreateModel(
            name='NovaPoshtaStreet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.NovaPoshtaCity')),
                ('type_street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.TypeStreet')),
            ],
            options={
                'unique_together': {('city', 'ref')},
            },
        ),
        migrations.CreateModel(
            name='NovaPoshtaDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_courier', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('other_street', models.CharField(blank=True, max_length=200, null=True)),
                ('house', models.CharField(blank=True, max_length=20, null=True)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.NovaPoshtaCity')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.NovaPoshtaStreet')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.NovaPoshtaWarehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='type_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.TypeDescription'),
        ),
    ]
