# Generated by Django 2.2 on 2020-05-20 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sailor', '0054_auto_20200520_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureForProtocolDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_base64', models.TextField(blank=True, null=True)),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='signature/')),
                ('protocol_dkk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sailor.ProtocolDKK')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
