# Generated by Django 2.2 on 2020-05-21 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0056_remove_experincefordkk_month_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature', '0002_vchasnologging'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionerSignProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_base64', models.TextField(blank=True, null=True)),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='signature/')),
                ('is_signatured', models.BooleanField(blank=True, null=True)),
                ('protocol_dkk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sailor.ProtocolDKK')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='vchasnologging',
            name='signature_for_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='signature.CommissionerSignProtocol'),
        ),
        migrations.DeleteModel(
            name='SignatureForProtocolDKK',
        ),
    ]
