# Generated by Django 2.2 on 2020-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_auto_20200521_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionersignprotocol',
            name='commissioner_type',
            field=models.CharField(choices=[('SC', 'Секретар'), ('HD', 'Голова'), ('CH', 'Член комісії')], default='SC', max_length=2),
        ),
    ]
