# Generated by Django 2.2 on 2020-05-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0004_commissionersignprotocol_commissioner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='protocol_dkk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commissioner_sign', to='sailor.ProtocolDKK'),
        ),
    ]
