# Generated by Django 2.2 on 2020-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_auto_20200521_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='is_signatured',
            field=models.BooleanField(default=False),
        ),
    ]
