# Generated by Django 2.2 on 2020-05-23 11:52

from django.db import migrations, models
import signature.models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0006_auto_20200521_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='signature_file',
            field=models.FileField(blank=True, null=True, upload_to=signature.models.get_upload_path),
        ),
    ]
