# Generated by Django 2.2 on 2020-05-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0007_auto_20200523_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='protocol_dkk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioner_sign', to='sailor.ProtocolDKK'),
        ),
    ]
