# Generated by Django 2.2 on 2020-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0008_auto_20200526_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionersignprotocol',
            name='signature_type',
            field=models.CharField(choices=[('signature', 'Signature'), ('stamp', 'Stamp')], default='signature', max_length=15),
        ),
    ]
