# Generated by Django 2.2 on 2020-05-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0009_commissionersignprotocol_signature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='signature_type',
            field=models.CharField(choices=[('signature', 'Signature'), ('stamp', 'Stamp')], default='signature', max_length=15),
        ),
    ]
