# Generated by Django 2.2 on 2020-08-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0010_auto_20200526_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='protocol_dkk',
            field=models.IntegerField(),
        ),
    ]
