# Generated by Django 2.2 on 2020-08-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0011_auto_20200811_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='protocol_dkk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioner_sign', to='document.ProtocolDKK'),
        ),
    ]
