# Generated by Django 2.2 on 2020-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signature', '0012_auto_20200811_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='protocol_dkk',
            field=models.IntegerField(),
        ),
    ]
