# Generated by Django 2.2 on 2020-08-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('signature', '0013_auto_20200822_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='protocol_dkk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioner_sign',
                                    to='document.ProtocolSQC'),
        ),
    ]
