# Generated by Django 2.2 on 2020-08-26 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0036_auto_20200825_1625'),
        ('signature', '0014_auto_20200822_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionersignprotocol',
            name='signer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='directory.Commisioner'),
        ),
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
