# Generated by Django 2.2 on 2020-08-26 13:07

from django.db import migrations

from signature.utils import forward_func_remove_user


def reverse_func(*args, **kwargs):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('signature', '0015_auto_20200826_1102'),
        ('document', '0021_auto_20200825_1625'),
    ]

    operations = [
        migrations.RunPython(forward_func_remove_user, reverse_func),
    ]
