# Generated by Django 2.2 on 2020-08-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signature', '0016_auto_20200826_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionersignprotocol',
            name='signer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='signed_items', to='directory.Commisioner'),
        ),
    ]
