# Generated by Django 3.1 on 2020-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signature', '0017_auto_20200826_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vchasnologging',
            name='params',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vchasnologging',
            name='response',
            field=models.JSONField(),
        ),
    ]
