# Generated by Django 3.1 on 2020-10-19 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinvitation',
            options={'permissions': (('agent_admin_agency', 'Агент админ агенства'),)},
        ),
    ]
