# Generated by Django 3.1.1 on 2020-11-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20201019_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinvitation',
            options={'permissions': (('agent_admin_agency', 'Add new agent by agent'),)},
        ),
    ]
