# Generated by Django 3.1.1 on 2020-11-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20201102_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinvitation',
            options={'permissions': (('agent_admin_agency', 'Set agent as admin'),)},
        ),
    ]
