# Generated by Django 3.1.1 on 2020-10-28 13:53

from datetime import date, timedelta

import django.utils.timezone
from django.db import migrations, models


def create_start_date(apps, schema_editor):
    date_start = date.today() - timedelta(days=1)
    PriceIORequest = apps.get_model('back_office', 'PriceIORequest')
    PriceIORequest.objects.create(date_start=date_start)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIORequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=0.0)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('type_of_form', models.CharField(choices=[('First', 'First')], default='First', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_start_date)
    ]
