# Generated by Django 3.1.1 on 2020-12-14 14:46

from datetime import date

import django.utils.timezone
from django.db import migrations, models


def create_start_data(apps, schema_editor):
    DeadweightPricePeriod = apps.get_model('back_office', 'DeadweightPricePeriod')
    validity = DeadweightPricePeriod.objects.create(date_start=date.today())
    DeadweightPrice = apps.get_model('back_office', 'DeadweightPrice')
    DeadweightPrice.objects.create(price_period=validity, price=0.0, from_deadweight=0)


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadweightPricePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeadweightPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_deadweight', models.FloatField()),
                ('to_deadweight', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('price_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices',
                                                   to='back_office.deadweightpriceperiod')),
            ],
        ),
        migrations.RunPython(create_start_data)
    ]
