# Generated by Django 3.1.1 on 2020-09-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='image',
            field=models.FileField(null=True, upload_to='flags/'),
        ),
    ]
