# Generated by Django 3.1.1 on 2020-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_staffposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('is_disable', models.BooleanField(default=False)),
                ('position_capitan_ukr', models.CharField(blank=True, default='', max_length=255)),
                ('position_capitan_eng', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='flag',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='staffposition',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typevessel',
            old_name='value',
            new_name='name',
        ),
    ]
