# Generated by Django 3.1.1 on 2020-09-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20200914_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('is_disable', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
