# Generated by Django 3.1.1 on 2020-09-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_statusdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdocument',
            name='service',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='statusdocument',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
