# Generated by Django 3.1.1 on 2020-10-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0006_auto_20200929_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTypeDocumnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('is_disable', models.BooleanField(default=False)),
                ('event',
                 models.CharField(choices=[('Input', 'Input'), ('Output', 'Output'), ('Input/Output', 'Input/Output')],
                                  default='Input/Output', max_length=20)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                            to='directory.grouptypedocumnet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
