# Generated by Django 3.1 on 2020-10-12 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0008_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('type_contact', models.CharField(
                    choices=[('phone', 'phone'), ('viber', 'viber'), ('telegram', 'telegram'), ('email', 'email')],
                    default='phone', max_length=20)),
                ('is_disable', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
