# Generated by Django 3.1 on 2020-10-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0009_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='EDRPOU',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_requisites',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='post_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
