# Generated by Django 3.1 on 2020-10-13 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import port_back.middleware


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0010_auto_20201012_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='author',
            field=models.ForeignKey(default=port_back.middleware.get_current_authenticated_user, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
