# Generated by Django 3.1 on 2020-10-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0011_agency_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
