# Generated by Django 3.1.1 on 2020-11-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_country_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='value_abbr',
            new_name='name_abbr',
        ),
        migrations.RemoveField(
            model_name='country',
            name='value',
        ),
    ]
