# Generated by Django 3.1.1 on 2021-01-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_harbormaster_port'),
        ('directory', '0014_auto_20201102_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='harbor_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports', to='core.harbormaster'),
        ),
    ]
