# Generated by Django 3.1.1 on 2021-01-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_auto_20210120_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='bank_requisites',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='name',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='passport',
        ),
        migrations.AddField(
            model_name='agency',
            name='IBAN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='MFO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='full_name',
            field=models.CharField(default='agency', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='short_name',
            field=models.CharField(default='agency', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='EDRPOU',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
