# Generated by Django 3.1.1 on 2021-02-01 09:13

import directory.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import port_back.middleware


class Migration(migrations.Migration):

    replaces = [('directory', '0020_towingcompany_towingcompanydocs'), ('directory', '0021_auto_20210129_1556'), ('directory', '0022_auto_20210201_0913')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0019_auto_20210126_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('short_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('post_address', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('IBAN', models.CharField(default='', max_length=50)),
                ('MFO', models.CharField(default='', max_length=50)),
                ('EDRPOU', models.CharField(default='', max_length=50)),
                ('author', models.ForeignKey(default=port_back.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.statusdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TowingCompanyDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to=directory.models.towing_company_docs_upload_path)),
                ('towing_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towing_company_docs', to='directory.towingcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('IMO', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=255)),
                ('power', models.CharField(max_length=255)),
                ('busy_to', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(default=port_back.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tow', to='directory.port')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.statusdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TowDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to=directory.models.tow_docs_upload_path)),
                ('towing_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tow_docs', to='directory.tow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
