# Generated by Django 3.1.1 on 2021-02-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_towingcompany_towingcompanydocs_squashed_0022_auto_20210201_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tow',
            name='IMO',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tow',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tows', to='directory.port'),
        ),
        migrations.AlterField(
            model_name='towingcompany',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
    ]
