# Generated by Django 2.2 on 2020-01-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sailor', '0017_auto_20200128_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsToVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sailor_key', models.PositiveIntegerField()),
                ('datetime_add', models.DateTimeField(auto_now_add=True)),
                ('type_document', models.CharField(max_length=150)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.Profile')),
            ],
            options={
                'unique_together': {('sailor_key', 'content_type', 'object_id')},
            },
        ),
    ]
