# Generated by Django 3.1.1 on 2020-09-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipkey',
            name='main_info',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
