# Generated by Django 3.1.1 on 2020-09-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_shipkey_main_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipkey',
            old_name='main_info',
            new_name='maininfo',
        ),
    ]
