# Generated by Django 3.1.1 on 2020-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20200911_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipkey',
            name='id',
        ),
        migrations.AlterField(
            model_name='shipkey',
            name='maininfo',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
