# Generated by Django 3.1.1 on 2020-09-11 11:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20200911_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipkey',
            name='shipstaff',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
