# Generated by Django 3.1.1 on 2020-09-28 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_shipkey_shipstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipkey',
            name='iorequest',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
