# Generated by Django 2.2 on 2019-12-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
