# Generated by Django 2.2 on 2019-12-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0002_auto_20191217_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitifcationdocument',
            name='position',
        ),
    ]
