# Generated by Django 2.2 on 2019-12-18 12:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0003_remove_qualitifcationdocument_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
