# Generated by Django 2.2 on 2019-12-27 17:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '__first__'),
        ('sailor', '0004_qualitifcationdocument_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='status_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalsertificate',
            name='limitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.LimitationForMedical'),
        ),
        migrations.CreateModel(
            name='StatemenetQualificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_create', models.DateField()),
                ('sailor', pgcrypto.fields.IntegerPGPSymmetricKeyField()),
                ('photo', pgcrypto.fields.IntegerPGPSymmetricKeyField(blank=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Position')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.ResponsibleForStatementDKK')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.TypeDocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_document', models.IntegerField()),
                ('date_meeting', models.DateField(blank=True, null=True)),
                ('commisioners', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('branch_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.BranchOffice')),
                ('committe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Committe')),
                ('statement_dkk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sailor.SailorStatementDKK')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
        ),
    ]
