# Generated by Django 2.2 on 2020-01-12 10:24

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '__first__'),
        ('sailor', '0005_auto_20191227_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.TextField()),
                ('key_document', django.contrib.postgres.fields.jsonb.JSONField()),
                ('document_description', models.TextField()),
                ('standarts_text', models.TextField()),
                ('for_what', models.CharField(choices=[('both', 'both'), ('continue', 'continue'), ('start', 'start')], default='both', max_length=10)),
                ('limitation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Limitations')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Position')),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfWorkDiploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_document', models.CharField(max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_continue', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='addictiondkk',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='addictiondkk',
            name='position',
        ),
        migrations.DeleteModel(
            name='DocumentKeys',
        ),
        migrations.RemoveField(
            model_name='temporarytable',
            name='limitation_id',
        ),
        migrations.RemoveField(
            model_name='temporarytable',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='qualitifcationdocument',
            name='city',
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.Country'),
        ),
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='is_continue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='is_continue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='protocol_dkk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.ProtocolDKK'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Position'),
        ),
        migrations.AlterField(
            model_name='sailorstatementdkk',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statemenetqualificationdocument',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='AddictionDKK',
        ),
        migrations.DeleteModel(
            name='TemporaryTable',
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='diploma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sailor.QualitifcationDocument'),
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='status_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument'),
        ),
    ]
