# Generated by Django 2.2 on 2020-01-16 18:22

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('sailor', '0006_auto_20200112_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 16, 20, 22, 45, 889185)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='port',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.Port'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='ports_input',
            field=models.TextField(),
        ),
        # migrations.AlterField(
        #     model_name='medicalsertificate',
        #     name='position',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        # ),
    ]
