# Generated by Django 2.2 on 2020-01-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_decision'),
        ('sailor', '0007_auto_20200116_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='decision',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='directory.Decision'),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.StatemenetQualificationDocument'),
        ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='directory.Country'),
        ),
        migrations.AlterField(
            model_name='statemenetqualificationdocument',
            name='type_document',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to='directory.TypeDocument'),
        ),
    ]
