# Generated by Django 2.2 on 2020-01-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_decision'),
        ('sailor', '0008_auto_20200116_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='port',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.Port'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='number_document',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='number_document',
            field=models.IntegerField(),
        ),
    ]
