# Generated by Django 2.2 on 2020-01-21 09:00

from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_decision'),
        ('sailor', '0009_auto_20200118_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineinservicerecord',
            name='full_name_master_eng',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='fio_captain_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='fio_captain_ukr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='port',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.Port'),
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sailor.StatemenetQualificationDocument'),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='fio_captain_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='fio_captain_ukr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        ),
    ]
