# Generated by Django 2.2 on 2020-01-22 17:03

from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_decision'),
        ('sailor', '0010_auto_20200121_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='num_flat',
            new_name='city_registration',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='index_place',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street_number_house',
        ),
        migrations.AddField(
            model_name='lineinservicerecord',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resident',
            field=pgcrypto.fields.IntegerPGPSymmetricKeyField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='other_port',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='protocoldkk',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='other_port',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sailoreducation',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sailorpassport',
            name='other_port',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        # migrations.AlterField(
        #     model_name='medicalsertificate',
        #     name='photo',
        #     field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        # ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=pgcrypto.fields.IntegerPGPSymmetricKeyField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='port',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Port'),
        ),
        # migrations.AlterField(
        #     model_name='qualitifcationdocument',
        #     name='photo',
        #     field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        # ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Port'),
        ),
        # migrations.AlterField(
        #     model_name='sailoreducation',
        #     name='photo',
        #     field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=250, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='sailorpassport',
        #     name='photo',
        #     field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        # ),
        migrations.AlterField(
            model_name='sailorpassport',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Port'),
        ),
        # migrations.AlterField(
        #     model_name='sailorstatementdkk',
        #     name='photo',
        #     field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        # ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=8, null=True)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('house', models.CharField(blank=True, max_length=250, null=True)),
                ('flat', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.City')),
            ],
        ),
    ]
