# Generated by Django 2.2 on 2020-01-24 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20200124_1113'),
        ('sailor', '0011_auto_20200122_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResidentProfile',
            new_name='FullAddress',
        ),
        migrations.RemoveField(
            model_name='medicalsertificate',
            name='sailor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='INN',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city_registration',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='qualitifcationdocument',
            name='sailor',
        ),
        migrations.RemoveField(
            model_name='sailoreducation',
            name='sailor',
        ),
        migrations.RemoveField(
            model_name='sailorpassport',
            name='sailor',
        ),
        migrations.RemoveField(
            model_name='servicerecordsailor',
            name='sailor',
        ),
        migrations.AddField(
            model_name='passport',
            name='city_birth',
            field=models.ForeignKey(blank=True, default=251, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.City'),
        ),
        migrations.AddField(
            model_name='passport',
            name='city_registration',
            field=pgcrypto.fields.IntegerPGPSymmetricKeyField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='inn',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='passport',
            name='resident',
            field=pgcrypto.fields.IntegerPGPSymmetricKeyField(blank=True, null=True),
        ),
    ]
