# Generated by Django 2.2 on 2020-01-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0012_auto_20200124_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
