# Generated by Django 2.2 on 2020-01-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0014_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoreducation',
            name='registry_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
