# Generated by Django 2.2 on 2020-01-28 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0015_sailoreducation_registry_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoreducation',
            name='experied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='full_name_master',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='responsibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='passport',
            name='serial',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sailoreducation',
            name='registry_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
