# Generated by Django 2.2 on 2020-01-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0016_auto_20200128_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='directory.Country'),
        ),
    ]
