# Generated by Django 2.2 on 2020-01-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0017_auto_20200128_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulladdress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.City'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='city_birth',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.City'),
        ),
    ]
