# Generated by Django 2.2 on 2020-02-03 09:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0018_auto_20200130_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='strict_blank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='function_limitation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='new_document',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='strict_blank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocoldkk',
            name='statement_dkk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.SailorStatementDKK'),
        ),
    ]
