# Generated by Django 2.2 on 2020-02-04 18:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20200204_2043'),
        ('sailor', '0019_auto_20200203_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='list_positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.Rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='list_positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.Rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='list_positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.Rank'),
            preserve_default=False,
        ),
    ]
