# Generated by Django 2.2 on 2020-02-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0020_auto_20200204_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalsertificate',
            name='position',
        ),
    ]
