# Generated by Django 2.2 on 2020-02-04 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20200204_2043'),
        ('sailor', '0021_remove_medicalsertificate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsertificate',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directory.PositionForMedical'),
            preserve_default=False,
        ),
    ]
