# Generated by Django 2.2 on 2020-02-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20200204_2043'),
        ('sailor', '0022_medicalsertificate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='branch_office',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.PROTECT, to='directory.BranchOffice'),
            preserve_default=False,
        ),
    ]
