# Generated by Django 2.2 on 2020-02-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0023_sailorstatementdkk_branch_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='number_document',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='number_document',
            field=models.BigIntegerField(),
        ),
    ]
