# Generated by Django 2.2 on 2020-02-07 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0024_auto_20200207_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='diploma_year',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='strict_blank',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='strict_blank',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
