# Generated by Django 2.2 on 2020-02-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0025_auto_20200207_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecordsailor',
            name='blank_strict_report',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
