# Generated by Django 2.2 on 2020-02-08 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sailor', '0026_auto_20200208_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='author',
            field=models.ForeignKey(default=161, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
