# Generated by Django 2.2 on 2020-02-09 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0027_protocoldkk_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoldkk',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sailorstatementdkk',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
