# Generated by Django 2.2 on 2020-02-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0028_auto_20200209_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineinservicerecord',
            name='number_page_book',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
