# Generated by Django 2.2 on 2020-02-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0029_lineinservicerecord_number_page_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Port'),
        ),
    ]
