# Generated by Django 2.2 on 2020-02-12 09:43

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0030_auto_20200211_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        ),
        # migrations.AlterField(
        #     model_name='servicerecordsailor',
        #     name='photo',
        #     field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        # ),
    ]
