# Generated by Django 2.2 on 2020-02-21 16:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20200208_2045'),
        ('sailor', '0031_auto_20200212_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='country_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_birth', to='directory.Country'),
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='function_limitation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofworkdiploma',
            name='other_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='other_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='number_page_book',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='number_document',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='number_document',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
