# Generated by Django 2.2 on 2020-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0032_auto_20200221_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineinservicerecord',
            name='port_of_registration',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
