# Generated by Django 2.2 on 2020-02-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0033_lineinservicerecord_port_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='ship_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
