# Generated by Django 2.2 on 2020-03-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20200303_1304'),
        ('sailor', '0034_auto_20200229_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='is_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experincefordkk',
            name='experince_descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experincefordkk',
            name='standarts_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='service_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sailor.ServiceRecordSailor'),
        ),
        migrations.AlterUniqueTogether(
            name='passport',
            unique_together={('serial', 'inn', 'country')},
        ),
    ]
