# Generated by Django 2.2 on 2020-03-05 15:37
import gm2m
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sailor', '0035_auto_20200303_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='related_docs',
            field=gm2m.fields.GM2MField('document.Education', 'document.CertificateETI',
                                        'document.QualificationDocument', 'document.ProofOfWorkDiploma',
                                        'document.MedicalCertificate', 'sailor.DependencyDocuments',
                                        blank=True, related_name='related_protocol',
                                        through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
        migrations.AddField(
            model_name='qualitifcationdocument',
            name='related_docs',
            field=gm2m.fields.GM2MField('document.Education', 'document.CertificateETI',
                                        'document.QualificationDocument', 'document.ProofOfWorkDiploma',
                                        'document.MedicalCertificate', 'sailor.DependencyDocuments',
                                        blank=True, related_name='related_qualification',
                                        through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='related_docs',
            field=gm2m.fields.GM2MField('document.Education', 'document.CertificateETI',
                                        'document.QualificationDocument', 'document.ProofOfWorkDiploma',
                                        'document.MedicalCertificate',
                                        'sailor.DependencyDocuments', blank=True, related_name='related_state_pr',
                                        through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='related_docs',
            field=gm2m.fields.GM2MField('document.Education', 'document.CertificateETI',
                                        'document.QualificationDocument', 'document.ProofOfWorkDiploma',
                                        'document.MedicalCertificate', 'sailor.DependencyDocuments',
                                        blank=True, related_name='related_state_qu',
                                        through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
