# Generated by Django 2.2 on 2020-03-06 14:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20200303_1304'),
        ('sailor', '0036_auto_20200305_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='function_limitation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='on_create_rank',
            field=models.ManyToManyField(related_name='on_create_rank', to='directory.Rank'),
        ),
    ]
