# Generated by Django 2.2 on 2020-03-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0037_auto_20200306_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoreducation',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sailorpassport',
            name='date_renewal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
