# Generated by Django 2.2 on 2020-03-31 09:51

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0039_medicalsertificate_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='sailor',
            field=pgcrypto.fields.IntegerPGPSymmetricKeyField(default=None, null=True),
        ),
    ]
