# Generated by Django 2.2 on 2020-03-31 15:28

import datetime

import django.contrib.postgres.fields
import django.db.models.deletion
import gm2m
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_rank_priority'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sailor', '0040_protocoldkk_sailor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocoldkk',
            old_name='sailor',
            new_name='_sailor',
        ),
        migrations.CreateModel(
            name='DemandPositionDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_positions',
                 django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_continue', models.BooleanField(default=False)),
                ('is_experience', models.BooleanField(default=False)),
                ('dependency_docs',
                 models.ManyToManyField(related_name='dependency_docs', to='sailor.DependencyDocuments')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Rank')),
                ('related_docs', gm2m.fields.GM2MField('document.Education', 'document.CertificateETI',
                                                       'document.QualificationDocument', 'document.ProofOfWorkDiploma',
                                                       'document.MedicalCertificate', 'sailor.DependencyDocuments',
                                                       blank=True, related_name='related_demand',
                                                       through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
                ('status_document',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
        ),
    ]
