# Generated by Django 2.2 on 2020-04-11 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('directory', '0012_rank_priority'),
        ('sailor', '0041_auto_20200331_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sailor', pgcrypto.fields.IntegerPGPSymmetricKeyField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
        ),
    ]
