# Generated by Django 2.2 on 2020-04-17 14:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0042_statementservicerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementservicerecord',
            name='photo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
