# Generated by Django 2.2 on 2020-04-18 11:21

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0043_auto_20200417_1709'),
    ]

    operations = [
    ]
