# Generated by Django 2.2 on 2020-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0044_auto_20200418_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementservicerecord',
            name='photo',
        ),
    ]
