# Generated by Django 2.2 on 2020-04-18 11:23

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0045_auto_20200418_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementservicerecord',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        ),
    ]
