# Generated by Django 2.2 on 2020-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0046_auto_20200418_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='experincefordkk',
            name='month_required',
            field=models.PositiveSmallIntegerField(default='6'),
        ),
    ]
