# Generated by Django 2.2 on 2020-05-04 10:04

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0047_experincefordkk_month_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemenetqualificationdocument',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True),
        ),
    ]
