# Generated by Django 2.2 on 2020-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0048_auto_20200504_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='userexam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
