# Generated by Django 2.2 on 2020-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0049_sailorstatementdkk_userexam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
