# Generated by Django 2.2 on 2020-05-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0050_protocoldkk_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
