# Generated by Django 2.2 on 2020-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0051_auto_20200515_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='is_printed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='is_cadet',
            field=models.BooleanField(default=False),
        ),
    ]
