# Generated by Django 2.2 on 2020-05-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0052_auto_20200518_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocoldkk',
            old_name='is_printed',
            new_name='is_printeble',
        ),
    ]
