# Generated by Django 2.2 on 2020-05-20 15:04

from django.db import migrations, models
import sailor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0053_auto_20200518_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoldkk',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=sailor.models.get_upload_path_protocol),
        ),
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='protocols/'),
        ),
    ]
