# Generated by Django 2.2 on 2020-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0054_auto_20200520_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statemenetqualificationdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='protocoldkk',
            name='vchasno_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
