# Generated by Django 2.2 on 2020-05-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0055_auto_20200520_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experincefordkk',
            name='month_required',
        ),
    ]
