# Generated by Django 2.2 on 2020-05-21 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0056_remove_experincefordkk_month_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoldkk',
            name='commisioners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
