# Generated by Django 2.2 on 2020-05-23 11:52

from django.db import migrations, models
import sailor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0057_auto_20200521_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocoldkk',
            old_name='document_file',
            new_name='document_file_docx',
        ),
        migrations.AddField(
            model_name='protocoldkk',
            name='document_file_pdf',
            field=models.FileField(blank=True, null=True, upload_to=sailor.models.get_upload_path_protocol),
        ),
    ]
