# Generated by Django 2.2 on 2020-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0058_auto_20200523_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
