# Generated by Django 2.2 on 2020-06-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_responsibilityworkbook'),
        ('sailor', '0060_statemenetqualificationdocument_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineinservicerecord',
            name='days_repair',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineinservicerecord',
            name='days_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineinservicerecord',
            name='is_repaired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineinservicerecord',
            name='place_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lineinservicerecord',
            name='record_type',
            field=models.CharField(blank=True, choices=[('Трудова книжка, довідка про фаховий стаж, ремонт, практику, тощо', 'Трудова книжка, довідка про фаховий стаж, ремонт, практику, тощо'), ('Довідка про стаж плавання', 'Довідка про стаж плавання')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lineinservicerecord',
            name='repair_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineinservicerecord',
            name='repair_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineinservicerecord',
            name='responsibility_work_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.ResponsibilityWorkBook'),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='date_write',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='full_name_master',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='full_name_master_eng',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='mode_of_navigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.ModeOfNavigation'),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='name_vessel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='number_vessel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='place_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='place_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='ports_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.PositionForExperience'),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='propulsion_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='trading_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='type_geu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.TypeGeu'),
        ),
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='type_vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.TypeVessel'),
        ),
        migrations.CreateModel(
            name='ResponsibilityServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('days_work', models.IntegerField(blank=True, null=True)),
                ('is_repaired', models.BooleanField(default=False)),
                ('responsibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Responsibility')),
                ('service_record_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_record_line', to='sailor.LineInServiceRecord')),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
    ]
