# Generated by Django 2.2 on 2020-06-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0061_auto_20200602_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='experincefordkk',
            name='month_required',
            field=models.PositiveSmallIntegerField(default='6'),
        ),
    ]
