# Generated by Django 2.2 on 2020-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0062_experincefordkk_month_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecordsailor',
            name='waibill_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
