# Generated by Django 2.2 on 2020-06-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0063_servicerecordsailor_waibill_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sailorpassport',
            options={'verbose_name': 'Посвідчення особи моряка'},
        ),
    ]
