# Generated by Django 2.2 on 2020-06-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0064_auto_20200620_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineinservicerecord',
            options={'verbose_name': 'Запис в ПКМ або довідка про стаж'},
        ),
        migrations.AlterModelOptions(
            name='medicalsertificate',
            options={'verbose_name': 'Медична справка'},
        ),
        migrations.AlterModelOptions(
            name='proofofworkdiploma',
            options={'verbose_name': 'Підтвердження к диплому'},
        ),
        migrations.AlterModelOptions(
            name='qualitifcationdocument',
            options={'verbose_name': 'Кваліфікаційний документ'},
        ),
        migrations.AlterModelOptions(
            name='sailoreducation',
            options={'verbose_name': 'Освітні документи'},
        ),
        migrations.AlterModelOptions(
            name='servicerecordsailor',
            options={'verbose_name': 'Послужна книжка моряка'},
        ),
    ]
