# Generated by Django 2.2 on 2020-07-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_ntz_is_disable'),
        ('sailor', '0065_auto_20200622_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementETI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.NTZ')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
        ),
    ]
