# Generated by Django 2.2 on 2020-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0066_statementeti'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementeti',
            name='date_meeting',
            field=models.DateField(blank=True, null=True),
        ),
    ]
