# Generated by Django 3.0.8 on 2020-07-10 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0067_statementeti_date_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_last_name_ukr', models.CharField(max_length=200)),
                ('old_last_name_eng', models.CharField(max_length=200)),
                ('old_first_name_ukr', models.CharField(max_length=200)),
                ('old_first_name_eng', models.CharField(max_length=200)),
                ('old_middle_name_ukr', models.CharField(max_length=200)),
                ('old_middle_name_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('new_last_name_ukr', models.CharField(max_length=200)),
                ('new_last_name_eng', models.CharField(max_length=200)),
                ('new_first_name_ukr', models.CharField(max_length=200)),
                ('new_first_name_eng', models.CharField(max_length=200)),
                ('new_middle_name_ukr', models.CharField(max_length=200)),
                ('new_middle_name_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('change_date', models.DateField()),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_name', to='sailor.Profile')),
            ],
        ),
    ]
