# Generated by Django 3.0.8 on 2020-07-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0068_oldname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailorstatementdkk',
            name='is_continue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statemenetqualificationdocument',
            name='is_continue',
            field=models.IntegerField(default=0),
        ),
    ]
