# Generated by Django 3.0.8 on 2020-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0069_auto_20200708_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandpositiondkk',
            name='is_continue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='is_continue',
            field=models.IntegerField(default=0),
        ),
    ]
