# Generated by Django 3.0.8 on 2020-07-21 17:17

from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields
import user_profile.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_auto_20200721_1841'),
        ('sailor', '0070_auto_20200711_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementSailorPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_payed', models.BooleanField(default=False)),
                ('is_continue', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Port')),
                ('sailor_passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='sailor.SailorPassport')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
            options={
                'verbose_name': 'Заява на посвідчення особи моряка',
            },
            bases=(models.Model, user_profile.mixins.GetAuthorMixin),
        ),
    ]
