# Generated by Django 3.0.8 on 2020-07-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0071_statementsailorpassport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificatentz',
            name='is_red',
            field=models.BooleanField(default=False),
        ),
    ]
