# Generated by Django 2.2 on 2020-07-30 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0029_auto_20200721_1841'),
        ('sailor', '0074_auto_20200730_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementMedicalCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_payed', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medical_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.MedicalInstitution')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.PositionForMedical')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
            options={
                'verbose_name': 'Заява медичне свідоцтво',
            },
        ),
    ]
