# Generated by Django 2.2 on 2020-07-30 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0030_levelqualification_course_time_hours'),
        ('sailor', '0075_statementmedicalcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementeti',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statementmedicalcertificate',
            name='date_meeting',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='StatementAdvancedTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_payed', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('photo', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=200, null=True)),
                ('date_meeting', models.DateField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('educational_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.NZ')),
                ('level_qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.LevelQualification')),
                ('status_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.StatusDocument')),
            ],
            options={
                'verbose_name': 'Заява на свідоцтво про підвищення кваліфікації',
            },
        ),
    ]
