# Generated by Django 2.2 on 2020-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0076_auto_20200730_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsailorpassport',
            name='date_meeting',
            field=models.DateField(null=True),
        ),
    ]
