# Generated by Django 2.2 on 2020-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0077_statementsailorpassport_date_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementeti',
            name='date_end_meeting',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='statementeti',
            name='is_continue',
            field=models.BooleanField(default=False),
        ),
    ]
