# Generated by Django 2.2 on 2020-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0078_auto_20200730_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementadvancedtraining',
            name='date_end_meeting',
            field=models.DateField(null=True),
        ),
    ]
