# Generated by Django 2.2 on 2020-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0079_statementadvancedtraining_date_end_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorstatementdkk',
            name='date_meeting',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='statemenetqualificationdocument',
            name='date_meeting',
            field=models.DateField(null=True),
        ),
    ]
