# Generated by Django 2.2 on 2020-08-04 14:50

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0080_auto_20200731_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificatentz',
            name='photo',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, max_length=250, null=True),
        ),
    ]
