# Generated by Django 2.2 on 2020-08-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0081_sertificatentz_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsertificate',
            name='medical_statement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.StatementMedicalCertificate'),
        ),
        migrations.AddField(
            model_name='sailoreducation',
            name='statement_advanced_training',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sailor.StatementAdvancedTraining'),
        ),
    ]
