# Generated by Django 2.2 on 2020-08-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0082_auto_20200807_1208'),
    ]

    database_operations = [
        migrations.AlterModelTable('StatementServiceRecord', 'statement_statementservicerecord')
    ]

    state_operations = [
        migrations.DeleteModel('StatementServiceRecord')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
