# Generated by Django 2.2 on 2020-08-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0083_auto_20200808_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INN',
        ),
    ]
