# Generated by Django 2.2 on 2020-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0084_delete_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoreducation',
            name='statement_advanced_training',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
