# Generated by Django 2.2 on 2020-08-08 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sailor', '0085_auto_20200808_1408'),
    ]

    database_operations = [
        migrations.AlterModelTable('StatementAdvancedTraining', 'statement_statementadvancedtraining')
    ]

    state_operations = [
        migrations.DeleteModel('StatementAdvancedTraining')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
