# Generated by Django 2.2 on 2020-08-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0086_auto_20200808_1408'),
        ('statement', '0002_statementadvancedtraining')
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoreducation',
            name='statement_advanced_training',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='statement.StatementAdvancedTraining'),
        ),
    ]
