# Generated by Django 2.2 on 2020-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0087_auto_20200808_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalsertificate',
            name='medical_statement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
