# Generated by Django 2.2 on 2020-08-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0088_auto_20200808_1419'),
    ]

    database_operations = [
        migrations.AlterModelTable('StatementMedicalCertificate', 'statement_statementmedicalcertificate')
    ]

    state_operations = [
        migrations.DeleteModel('StatementMedicalCertificate')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
