# Generated by Django 2.2 on 2020-08-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0089_auto_20200808_1420'),
        ('statement', '0003_statementmedicalcertificate')
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalsertificate',
            name='medical_statement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='statement.StatementMedicalCertificate'),
        ),
    ]
