# Generated by Django 2.2 on 2020-08-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0090_auto_20200808_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoldkk',
            name='statement_dkk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
