# Generated by Django 2.2 on 2020-08-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0091_auto_20200808_1430'),
        ('docs', '0004_auto_20200808_1430')
    ]

    database_operations = [
        migrations.AlterModelTable('SailorStatementDKK', 'statement_sailorstatementdkk')
    ]

    state_operations = [
        migrations.DeleteModel('SailorStatementDKK')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
