# Generated by Django 2.2 on 2020-08-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0092_auto_20200808_1432'),
        ('statement', '0004_sailorstatementdkk')
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoldkk',
            name='statement_dkk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='statement.SailorStatementDKK'),
        ),
    ]
