# Generated by Django 2.2 on 2020-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0093_auto_20200808_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='statement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='statement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
