# Generated by Django 2.2 on 2020-08-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0094_auto_20200808_1632'),
        ('docs', '0006_auto_20200808_1632')
    ]

    database_operations = [
        migrations.AlterModelTable('StatemenetQualificationDocument', 'statement_statemenetqualificationdocument')
    ]

    state_operations = [
        migrations.DeleteModel('StatemenetQualificationDocument')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
