# Generated by Django 2.2 on 2020-08-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0095_auto_20200808_1634'),
        ('statement', '0005_statemenetqualificationdocument')
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statement.StatemenetQualificationDocument'),
        ),
        migrations.AlterField(
            model_name='qualitifcationdocument',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='statement.StatemenetQualificationDocument'),
        ),
    ]
