# Generated by Django 2.2 on 2020-08-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0096_auto_20200808_1639'),
    ]

    database_operations = [
        migrations.AlterModelTable('StatementETI', 'statement_statementeti')
    ]

    state_operations = [
        migrations.DeleteModel('StatementETI')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]