# Generated by Django 2.2 on 2020-08-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0097_auto_20200808_1653'),
    ]

    database_operations = [
        migrations.AlterModelTable('StatementSailorPassport', 'statement_statementsailorpassport')
    ]

    state_operations = [
        migrations.DeleteModel('StatementSailorPassport')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
