# Generated by Django 2.2 on 2020-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0098_auto_20200808_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='type_contact',
            field=models.IntegerField(),
        ),
    ]
