# Generated by Django 2.2 on 2020-08-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0099_auto_20200809_1323'),
    ]

    database_operations = [migrations.AlterModelTable('TypeContact', 'directory_typecontact')]

    state_operations = [migrations.DeleteModel('TypeContact')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
