# Generated by Django 2.2 on 2020-08-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0100_auto_20200809_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='type_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.TypeContact'),
        ),
    ]
