# Generated by Django 2.2 on 2020-08-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0101_auto_20200809_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(),
        ),
    ]
