# Generated by Django 2.2 on 2020-08-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0102_auto_20200809_1508'),
    ]

    database_operations = [
        migrations.AlterModelTable('Sex', 'directory_sex')
    ]

    state_operations = [
        migrations.DeleteModel('Sex')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
