# Generated by Django 2.2 on 2020-08-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0103_auto_20200809_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Sex'),
        ),
    ]
