# Generated by Django 2.2 on 2020-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0104_auto_20200809_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='service_record',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
