# Generated by Django 2.2 on 2020-08-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0105_auto_20200809_1519'),
        ('docs', '0008_auto_20200809_1519')
    ]

    database_operations = [
        migrations.AlterModelTable('ServiceRecordSailor', 'document_servicerecordsailor')
    ]

    state_operations = [
        migrations.DeleteModel('ServiceRecordSailor')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
