# Generated by Django 2.2 on 2020-08-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0106_auto_20200809_1520'),
        ('document', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='lineinservicerecord',
            name='service_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='document.ServiceRecordSailor'),
        ),
    ]
