# Generated by Django 2.2 on 2020-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0107_auto_20200809_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibilityservicerecord',
            name='service_record_line',
            field=models.IntegerField(),
        ),
    ]
