# Generated by Django 2.2 on 2020-08-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0108_auto_20200809_1600'),
    ]

    database_operations = [
        migrations.AlterModelTable('LineInServiceRecord', 'document_lineinservicerecord')
    ]

    state_operations = [
        migrations.DeleteModel('LineInServiceRecord')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]