# Generated by Django 2.2 on 2020-08-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0109_auto_20200809_1600'),
        ('document', '0002_lineinservicerecord')
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibilityservicerecord',
            name='service_record_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_record_line', to='document.LineInServiceRecord'),
        ),
    ]
