# Generated by Django 2.2 on 2020-08-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0110_auto_20200809_1602'),
    ]

    database_operations = [
        migrations.AlterModelTable('TypeVessel', 'directory_typevessel'),
        migrations.AlterModelTable('ModeOfNavigation', 'directory_modeofnavigation'),
        migrations.AlterModelTable('TypeGeu', 'directory_typegeu')

    ]

    state_operations = [
        migrations.DeleteModel('TypeVessel'),
        migrations.DeleteModel('ModeOfNavigation'),
        migrations.DeleteModel('TypeGeu')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]