# Generated by Django 2.2 on 2020-08-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0111_auto_20200809_1627'),
    ]

    database_operations = [
        migrations.AlterModelTable('SailorEducation', 'document_sailoreducation')
    ]

    state_operations = [
        migrations.DeleteModel('SailorEducation')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
