# Generated by Django 2.2 on 2020-08-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0112_auto_20200809_1637'),
    ]

    database_operations = [
        migrations.AlterModelTable('ExperinceForDKK', 'directory_experincefordkk')
    ]

    state_operations = [
        migrations.DeleteModel('ExperinceForDKK')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
