# Generated by Django 2.2 on 2020-08-11 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sailor', '0113_auto_20200810_1911'),
    ]

    operations = [
        migrations.RunSQL(
            'alter table sailor_sailorstatementdkk_related_docs '
            'rename to statement_sailorstatementdkk_related_docs;'
        ),
        migrations.RunSQL(
            'alter table sailor_statemenetqualificationdocument_related_docs '
            'rename to statement_statemenetqualificationdocument_related_docs;'
        )
    ]
