# Generated by Django 2.2 on 2020-08-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0008_auto_20200811_1547'),
        ('sailor', '0114_auto_20200811_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponsibleForStatementDKK',
        ),
    ]
