# Generated by Django 2.2 on 2020-08-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0115_delete_responsibleforstatementdkk'),
    ]

    database_operations = [migrations.AlterModelTable('ProtocolDKK', 'document_protocoldkk')]

    state_operations = [migrations.DeleteModel('ProtocolDKK')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]