# Generated by Django 2.2 on 2020-08-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0116_auto_20200811_1754'),
    ]

    database_operations = [migrations.AlterModelTable('SertificateNTZ', 'document_sertificatentz')]

    state_operations = [migrations.DeleteModel('SertificateNTZ')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]