# Generated by Django 2.2 on 2020-08-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0117_auto_20200811_1854'),
    ]

    database_operations = [
        migrations.AlterModelTable('MedicalSertificate', 'document_medicalsertificate')
    ]

    state_operations = [
        migrations.DeleteModel('MedicalSertificate')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
