# Generated by Django 2.2 on 2020-08-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0118_auto_20200814_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='diploma',
            field=models.IntegerField(),
        ),
    ]
