# Generated by Django 2.2 on 2020-08-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0119_auto_20200814_0015'),
        ('docs', '0012_auto_20200814_0015')
    ]

    database_operations = [
        migrations.AlterModelTable('QualitifcationDocument', 'document_qualitifcationdocument')
    ]

    state_operations = [
        migrations.DeleteModel('QualitifcationDocument')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]