# Generated by Django 2.2 on 2020-08-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0120_auto_20200814_0018'),
        ('document', '0009_qualitifcationdocument')
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofworkdiploma',
            name='diploma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.QualitifcationDocument'),
        ),
    ]
