# Generated by Django 2.2 on 2020-08-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0121_auto_20200814_0056'),
    ]

    database_operations = [migrations.AlterModelTable('ProofOfWorkDiploma', 'document_proofofworkdiploma')]

    state_operations = [migrations.DeleteModel('ProofOfWorkDiploma')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
