# Generated by Django 2.2 on 2020-08-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0122_auto_20200814_1116'),
    ]

    database_operations = [migrations.AlterModelTable('ResponsibilityServiceRecord',
                                                      'document_responsibilityservicerecord')]

    state_operations = [migrations.DeleteModel('ResponsibilityServiceRecord')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
