# Generated by Django 2.2 on 2020-08-22 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sailor', '0123_auto_20200814_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
