# Generated by Django 3.1 on 2020-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sailor', '0124_remove_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencydocuments',
            name='key_document',
            field=models.JSONField(),
        ),
    ]
