# Generated by Django 3.1 on 2020-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0125_auto_20200826_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoprofile',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
