# Generated by Django 3.1 on 2020-10-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sailor', '0126_photoprofile_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldname',
            options={'ordering': ['-created_at', '-modified_at']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at', '-modified_at']},
        ),
        migrations.AddField(
            model_name='oldname',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='oldname',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sailorpassport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sailorpassport',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
