# Generated by Django 3.1 on 2020-10-22 09:30

from django.db import migrations
from django.db.models import F
import django.contrib.contenttypes.management


def update_dates(apps, schema_editor):
    app = apps.get_app_config('sailor')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    OldName = apps.get_model('sailor', 'OldName')
    OldName.objects.all().update(created_at=F('date_create'))


class Migration(migrations.Migration):
    dependencies = [
        ('sailor', '0127_auto_20201022_1229'),
    ]

    operations = [
        migrations.RunPython(update_dates),
        migrations.RemoveField(
            model_name='oldname',
            name='date_create',
        ),
    ]
