# Generated by Django 3.1 on 2020-10-22 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0128_auto_20201022_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at', '-modified_at']},
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
