# Generated by Django 3.1 on 2020-10-22 09:33

from django.db import migrations
import django.contrib.contenttypes.management
from django.db.models import F


def update_dates(apps, schema_editor):
    app = apps.get_app_config('sailor')
    app.models_module = app.models_module or True
    django.contrib.contenttypes.management.create_contenttypes(app)
    Rating = apps.get_model('contenttypes', 'Rating')
    Rating.objects.all().update(created_at=F('date_create'))


class Migration(migrations.Migration):
    dependencies = [
        ('sailor', '0129_auto_20201022_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='date_create',
        ),
    ]
