# Generated by Django 3.1 on 2020-10-22 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0130_remove_rating_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandpositiondkk',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
