# Generated by Django 3.1 on 2020-10-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0132_auto_20201022_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofile',
            name='photo',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
