# Generated by Django 3.1 on 2020-10-30 17:37

from django.db import migrations, models
import sailor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0135_auto_20201030_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofile',
            name='photo',
            field=models.ImageField(max_length=500, upload_to=sailor.models.get_upload_photo_path),
        ),
    ]
