# Generated by Django 3.1.1 on 2020-11-02 10:03

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import itcs.middleware


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0052_statusdocumentinverification'),
        ('sailor', '0136_auto_20201030_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                   to='contenttypes.contenttype')),
                ('verification_status',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   to='directory.statusdocumentinverification')),
            ],
            options={
                'ordering': ['verification_status__order_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentForVerificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(default='')),
                ('author', models.ForeignKey(default=itcs.middleware.get_current_authenticated_user, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments',
                                               to='sailor.documentinverification')),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'abstract': False,
            },
        ),
    ]
