# Generated by Django 3.1 on 2020-10-12 13:57

from django.db import migrations
import django.contrib.contenttypes.management


def add_dependency(apps, schema_editor):
    new_dep = {
        936: [{"position": 143, "type_document": 87}, {"position": 323, "type_document": 4},
              {"position": 47, "type_document": 4},  {"position": 143, "type_document": 4},
              {"position": 142, "type_document": 4},{"position": 327, "type_document": 4},
              {"position": 321, "type_document": 4},  {"position": 134, "type_document": 4}],
        937: [{"position": 148, "type_document": 87}, {"position": 146, "type_document": 5},
              {"position": 326, "type_document": 5}, {"position": 48, "type_document": 5},
              {"position": 148, "type_document": 5}],
        611: [{"position": 148, "type_document": 87}, {"position": 326, "type_document": 6},
              {"position": 147, "type_document": 6}],
        939: [{"position": 201, "type_document": 87}, {"position": 151, "type_document": 6},
              {"position": 341, "type_document": 6}, {"position": 442, "type_document": 6},
              {"position": 201, "type_document": 6}, {"position": 441, "type_document": 6},
              {"position": 131, "type_document": 6}],
        636: [{"position": 148, "type_document": 87}, {"position": 150, "type_document": 87},
              {"position": 149, "type_document": 87}, {"position": 151, "type_document": 87}]
    }
    app = apps.get_app_config('sailor')
    app.models_module = app.models_module or True
    DependencyDocuments = apps.get_model('sailor', 'DependencyDocuments')
    for dep_id, key_document in new_dep.items():
        dep = DependencyDocuments.objects.get(id=dep_id)
        dep.key_document = key_document
        dep.save(update_fields=['key_document'])


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0137_documentinverification_verificationcomment'),
    ]

    operations = [
        migrations.RunPython(add_dependency)
    ]