# Generated by Django 3.1 on 2020-12-29 08:43

from django.db import migrations, models

from sailor.models import SailorPassport


def old_sailor_passport(apps, schema_editor):
    SailorPassport.objects.all().filter(items__isnull=True).update(is_new_document=False)


class Migration(migrations.Migration):
    dependencies = [
        ('sailor', '0138_dependency_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorpassport',
            name='is_new_document',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name='sailorpassport',
            options={'permissions': (('readReportSailorPassport', 'Просмотр отчета по ПОМ'),),
                     'verbose_name': 'Посвідчення особи моряка'},
        ),
        migrations.RunPython(old_sailor_passport)
    ]
