# Generated by Django 3.1 on 2021-01-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0139_sailorpassport_is_new_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sailorpassport',
            options={'permissions': (('readReportSailorPassport', 'Просмотр отчета по ПОМ'), ('createNewSailorPassport', 'Создание нового паспорта моряка')), 'verbose_name': 'Посвідчення особи моряка'},
        ),
    ]
