# Generated by Django 2.2 on 2020-01-24 09:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='citizen_passport',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='sailorkeys',
            name='inn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
