# Generated by Django 2.2 on 2020-02-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_tmp_tmp1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tmp',
        ),
        migrations.DeleteModel(
            name='Tmp1',
        ),
    ]
