# Generated by Django 2.2 on 2020-03-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20200221_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
