# Generated by Django 2.2 on 2020-03-31 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_sailorkeys_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='demand_position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
