# Generated by Django 2.2 on 2020-04-11 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_sailorkeys_demand_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='statement_service_records',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
