# Generated by Django 2.2 on 2020-05-15 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_sailorkeys_statement_service_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='students_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
