# Generated by Django 2.2 on 2020-07-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_sailorkeys_students_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='agent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
