# Generated by Django 2.2 on 2020-07-01 12:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_sailorkeys_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='statement_eti',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
