# Generated by Django 3.0.8 on 2020-07-11 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_sailorkeys_statement_eti'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='packet_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
