# Generated by Django 2.2 on 2020-07-19 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_sailorkeys_packet_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailorkeys',
            name='service_records',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
