# Generated by Django 2.2 on 2020-07-19 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_auto_20200719_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailorkeys',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
