# Generated by Django 3.0.8 on 2020-07-20 07:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_auto_20200719_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailorkeys',
            name='statement_service_records',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
