# Generated by Django 3.0.8 on 2020-07-20 08:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_auto_20200720_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailorkeys',
            name='medical_sertificate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
