# Generated by Django 3.0.8 on 2020-07-20 08:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_auto_20200720_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailorkeys',
            name='sailor_passport',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
