# Generated by Django 3.0.8 on 2020-07-20 10:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0019_auto_20200720_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailorkeys',
            name='demand_position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
