# Generated by Django 3.0.8 on 2020-07-21 17:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0022_auto_20200720_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='statement_sailor_passport',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
