# Generated by Django 2.2 on 2020-07-30 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0023_sailorkeys_statement_sailor_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='statement_medical_certificate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
