# Generated by Django 2.2 on 2020-07-30 17:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0024_sailorkeys_statement_medical_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailorkeys',
            name='statement_advanced_training',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
