# Generated by Django 3.0.8 on 2020-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0002_historyuserinpersonalcabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
