# Generated by Django 2.2 on 2020-05-09 07:11

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status_response', models.IntegerField(blank=True, null=True)),
                ('descr', models.TextField(default='')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('inn', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100)),
                ('line_exit', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
