# Generated by Django 2.2 on 2020-05-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgovua_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationlog',
            name='descr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='authorizationlog',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationlog',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationlog',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationlog',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationlog',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
