# Generated by Django 3.1 on 2020-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('idgovua_auth', '0002_auto_20200509_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationlog',
            name='auth_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
