# Generated by Django 2.2 on 2020-03-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CcyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.PositiveSmallIntegerField()),
                ('code_str', models.CharField(max_length=3)),
                ('rate', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('send_time', models.DateTimeField()),
                ('system_id', models.IntegerField(unique_for_year='send_time')),
                ('amount', models.PositiveIntegerField()),
                ('ccy_code', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rrn', models.CharField(blank=True, max_length=50, null=True)),
                ('fee', models.PositiveIntegerField(null=True)),
                ('response_code', models.IntegerField(null=True)),
                ('pan_mask', models.CharField(blank=True, max_length=16, null=True)),
                ('pay_time', models.DateTimeField(null=True)),
                ('payment_no', models.BigIntegerField(null=True)),
                ('result', models.CharField(blank=True, max_length=5, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['system_id'], name='payments_pa_system__0ba8d6_idx'),
        ),
    ]
