# Generated by Django 2.2 on 2020-05-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_rank_priority'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='DescriptionForPaymentsForDKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Rank')),
            ],
        ),
    ]
