# Generated by Django 3.0.8 on 2020-07-21 08:47
from django.contrib.postgres.operations import CryptoExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CryptoExtension()
    ]
