# Generated by Django 2.2 on 2020-08-04 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPushData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('user_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.DevicesData')),
            ],
        ),
    ]
