# Generated by Django 3.1 on 2020-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0003_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypushdata',
            name='push_data',
            field=models.JSONField(),
        ),
    ]
