# Generated by Django 3.1 on 2020-10-22 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200826_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypushdata',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
